package main

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/stefanpenner/otel-explorer/tools/specgen/tla"
)

// GenerateRust produces an idiomatic Rust decision module for PATH A
// (named scalar actions only). Go remains the default language.
//
// Rust shape (not a Go transliteration):
//   - snake_case methods (can_open / open)
//   - Copy+Clone when all fields are Copy; else Clone
//   - consuming self for transitions (ownership = new state)
//   - pure predicates as &self methods + PURE_PREDICATES registry
//
// Unsupported (clear error via supportsRust): PATH B/C, maps/sets, non-scalars.
func (cg *CodeGen) supportsRust() error {
	if cg.Dispatch != nil {
		return fmt.Errorf("rust: Step-dispatch specs (PATH B) not supported yet; use -lang go or a named-action decision core")
	}
	if cg.isParamLib() {
		return fmt.Errorf("rust: parameterised actions (PATH C) not supported yet; use -lang go")
	}
	if len(cg.Actions) == 0 {
		return fmt.Errorf("rust: no named actions to generate")
	}
	for _, v := range cg.Spec.Variables {
		t := cg.inferType(v)
		switch t {
		case "bool", "int64", "string":
			// ok
		default:
			return fmt.Errorf("rust: variable %q has type %s (only bool, i64, String for now)", v, t)
		}
	}
	return nil
}

// GenerateRust returns the full Rust source for spec.rs.
func (cg *CodeGen) GenerateRust() string {
	var b strings.Builder
	cg.writeRustHeader(&b)
	cg.writeRustState(&b)
	cg.writeRustImpl(&b)
	cg.writeRustPurePredicates(&b)
	cg.writeRustTests(&b)
	return b.String()
}

func (cg *CodeGen) writeRustHeader(b *strings.Builder) {
	fmt.Fprintf(b, "// Code generated by specgen from %s — DO NOT EDIT.\n", stablePath(cg.SpecPath))
	b.WriteString("//\n")
	fmt.Fprintf(b, "// Source:     %s\n", stablePath(cg.SpecPath))
	fmt.Fprintf(b, "// Regenerate: %s\n", cg.regenCommandRust())
	b.WriteString("//\n")
	b.WriteString("// Edit the .tla, not this file. Language: Rust (PATH A decision core).\n")
	b.WriteString("// Package/module hint: ")
	b.WriteString(cg.pkgName())
	b.WriteString("\n\n")
}

func (cg *CodeGen) regenCommandRust() string {
	parts := []string{"specgen", "-lang", "rust"}
	for _, c := range cg.ConstFlags {
		parts = append(parts, "-const", c)
	}
	if cg.OutputDir != "" {
		parts = append(parts, "-o", stablePath(cg.OutputDir))
	}
	if cg.PackageName != "" {
		parts = append(parts, "-p", cg.PackageName)
	}
	source := cg.SpecPath
	if source == "" {
		source = cg.Spec.Name + ".tla"
	}
	parts = append(parts, stablePath(source))
	return strings.Join(parts, " ")
}

func (cg *CodeGen) rustAllCopy() bool {
	for _, v := range cg.Spec.Variables {
		if cg.inferType(v) == "string" {
			return false
		}
	}
	return true
}

func (cg *CodeGen) writeRustState(b *strings.Builder) {
	if cg.rustAllCopy() {
		b.WriteString("#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]\n")
	} else {
		b.WriteString("#[derive(Clone, Debug, Default, PartialEq, Eq)]\n")
	}
	b.WriteString("pub struct State {\n")
	for _, v := range cg.Spec.Variables {
		fmt.Fprintf(b, "\tpub %s: %s,\n", rustField(v), rustType(cg.inferType(v)))
	}
	b.WriteString("}\n\n")
}

func (cg *CodeGen) writeRustImpl(b *strings.Builder) {
	b.WriteString("impl State {\n")
	// init
	b.WriteString("\t/// Initial state from the TLA+ Init predicate.\n")
	b.WriteString("\tpub fn init() -> Self {\n")
	b.WriteString("\t\tSelf {\n")
	initBody := cg.Spec.FindDef("Init")
	for _, v := range cg.Spec.Variables {
		val := findInitVal(v, initBody)
		fmt.Fprintf(b, "\t\t\t%s: %s,\n", rustField(v), cg.litToRust(val))
	}
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")

	// actions
	for _, act := range cg.Actions {
		can := rustCanMethod(act.Name)
		do := rustMethod(act.Name)
		fmt.Fprintf(b, "\t/// Guard for action %s.\n", act.Name)
		fmt.Fprintf(b, "\tpub fn %s(&self) -> bool {\n", can)
		fmt.Fprintf(b, "\t\t%s\n", rustReturnExpr(cg.exprToRust(act.Guard, "self", false)))
		b.WriteString("\t}\n\n")

		fmt.Fprintf(b, "\t/// Apply action %s (consuming self — pure transition).\n", act.Name)
		fmt.Fprintf(b, "\tpub fn %s(self) -> Self {\n", do)
		// simultaneous assign: build from pre (only if read)
		touched := map[string]bool{}
		var fields strings.Builder
		for _, u := range act.Update {
			if isSelfAssign(u) {
				continue
			}
			touched[u.Var] = true
			fmt.Fprintf(&fields, "\t\t\t%s: %s,\n", rustField(u.Var), cg.exprToRust(u.Val, "pre", true))
		}
		for _, v := range cg.Spec.Variables {
			if touched[v] {
				continue
			}
			fmt.Fprintf(&fields, "\t\t\t%s: pre.%s,\n", rustField(v), rustField(v))
		}
		body := fields.String()
		if strings.Contains(body, "pre.") {
			b.WriteString("\t\tlet pre = self;\n")
		} else {
			// no field reads — drop unused self without warning
			b.WriteString("\t\tlet _ = self;\n")
		}
		b.WriteString("\t\tSelf {\n")
		b.WriteString(body)
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n\n")
	}

	// enabled_actions
	b.WriteString("\t/// Names of actions whose guards hold.\n")
	b.WriteString("\tpub fn enabled_actions(&self) -> Vec<&'static str> {\n")
	b.WriteString("\t\tlet mut out = Vec::new();\n")
	for _, act := range cg.Actions {
		fmt.Fprintf(b, "\t\tif self.%s() {\n", rustCanMethod(act.Name))
		fmt.Fprintf(b, "\t\t\tout.push(%q);\n", act.Name)
		b.WriteString("\t\t}\n")
	}
	b.WriteString("\t\tout\n")
	b.WriteString("\t}\n\n")

	// apply_action — peer of Go ApplyAction; name is TLA action id.
	b.WriteString("\t/// Apply a named action if its guard holds.\n")
	b.WriteString("\tpub fn apply_action(self, name: &str) -> Option<Self> {\n")
	b.WriteString("\t\tmatch name {\n")
	for _, act := range cg.Actions {
		fmt.Fprintf(b, "\t\t\t%q => {\n", act.Name)
		fmt.Fprintf(b, "\t\t\t\tif self.%s() {\n", rustCanMethod(act.Name))
		fmt.Fprintf(b, "\t\t\t\t\tSome(self.%s())\n", rustMethod(act.Name))
		b.WriteString("\t\t\t\t} else {\n")
		b.WriteString("\t\t\t\t\tNone\n")
		b.WriteString("\t\t\t\t}\n")
		b.WriteString("\t\t\t}\n")
	}
	b.WriteString("\t\t\t_ => None,\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
}

func (cg *CodeGen) writeRustPurePredicates(b *strings.Builder) {
	preds := cg.purePredicatesRust()
	if len(preds) == 0 {
		return
	}
	b.WriteString("impl State {\n")
	for _, p := range preds {
		fmt.Fprintf(b, "\t/// Pure TLA+ operator %s.\n", p.name)
		fmt.Fprintf(b, "\tpub fn %s(&self) -> bool {\n", rustMethod(p.name))
		fmt.Fprintf(b, "\t\t%s\n", rustReturnExpr(p.expr))
		b.WriteString("\t}\n\n")
	}
	b.WriteString("}\n\n")

	// Registry: name + method for dual enumeration (idiomatic const table).
	b.WriteString("/// Named pure predicates for dual/CI enumeration.\n")
	b.WriteString("pub struct PurePredicate {\n")
	b.WriteString("\tpub name: &'static str,\n")
	b.WriteString("\tpub check: fn(&State) -> bool,\n")
	b.WriteString("}\n\n")
	b.WriteString("/// Every pure operator emitted for this module.\n")
	b.WriteString("pub const PURE_PREDICATES: &[PurePredicate] = &[\n")
	for _, p := range preds {
		fmt.Fprintf(b, "\tPurePredicate { name: %q, check: State::%s },\n", p.name, rustMethod(p.name))
	}
	b.WriteString("];\n\n")
}

type rustPure struct {
	name string
	expr string
}

func (cg *CodeGen) purePredicatesRust() []rustPure {
	var out []rustPure
	actionNames := map[string]bool{}
	for _, a := range cg.Actions {
		actionNames[a.Name] = true
	}
	reserved := map[string]bool{
		"Init": true, "Next": true, "Spec": true, "TypeOK": true, "TypeOk": true, "vars": true,
	}
	for _, d := range cg.Spec.Defs {
		if reserved[d.Name] || actionNames[d.Name] || len(d.Params) > 0 {
			continue
		}
		// Match Go purePredicates: Bait* is TLC-only (must FAIL), not dual SSOT.
		if strings.HasPrefix(d.Name, "Bait") {
			continue
		}
		if cg.Spec.Recursive != nil && cg.Spec.Recursive[d.Name] {
			continue
		}
		if d.Body == nil || tla.HasPrimed(d.Body) {
			continue
		}
		inlined, err := tla.Inline(cg.Spec, d.Body)
		if err != nil {
			continue
		}
		expr := cg.exprToRust(inlined, "self", false)
		if expr == "" || strings.Contains(expr, "/* unsupported") {
			continue
		}
		out = append(out, rustPure{name: d.Name, expr: expr})
	}
	return out
}

func (cg *CodeGen) writeRustTests(b *strings.Builder) {
	b.WriteString("#[cfg(test)]\n")
	b.WriteString("mod tests {\n")
	b.WriteString("\tuse super::*;\n\n")
	b.WriteString("\t#[test]\n")
	b.WriteString("\tfn init_ok() {\n")
	b.WriteString("\t\tlet s = State::init();\n")
	b.WriteString("\t\tlet _ = s.enabled_actions();\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\t#[test]\n")
	b.WriteString("\tfn pure_predicates_no_panic() {\n")
	preds := cg.purePredicatesRust()
	if len(preds) == 0 {
		b.WriteString("\t\t// no pure predicates\n")
	} else {
		b.WriteString("\t\tlet s = State::init();\n")
		b.WriteString("\t\tassert_eq!(PURE_PREDICATES.len(), ")
		fmt.Fprintf(b, "%d);\n", len(preds))
		b.WriteString("\t\tfor p in PURE_PREDICATES {\n")
		b.WriteString("\t\t\tlet _ = (p.check)(&s);\n")
		b.WriteString("\t\t}\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
}

func rustType(goType string) string {
	switch goType {
	case "bool":
		return "bool"
	case "int64":
		return "i64"
	case "string":
		return "String"
	default:
		return "()"
	}
}

// rustField maps a TLA variable to a snake_case field name.
func rustField(name string) string { return toSnake(name) }

// rustMethod maps TurnOn / Inv_DepthNonNeg → turn_on / inv_depth_non_neg.
func rustMethod(name string) string { return toSnake(name) }

func rustCanMethod(action string) string { return "can_" + toSnake(action) }

// toSnake maps TLA/Go-ish names to snake_case without shredding acronyms:
// TurnOn → turn_on, haveAPI → have_api, Inv_DepthNonNeg → inv_depth_non_neg.
func toSnake(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	var b strings.Builder
	for i, r := range runes {
		if r == '_' {
			if b.Len() > 0 {
				out := b.String()
				if !strings.HasSuffix(out, "_") {
					b.WriteByte('_')
				}
			}
			continue
		}
		if unicode.IsUpper(r) {
			if i > 0 {
				prev := runes[i-1]
				nextLower := i+1 < len(runes) && unicode.IsLower(runes[i+1])
				// lower→Upper or acronym boundary UpperUpperLower
				if prev != '_' && (unicode.IsLower(prev) || unicode.IsDigit(prev) ||
					(unicode.IsUpper(prev) && nextLower)) {
					b.WriteByte('_')
				}
			}
			b.WriteRune(unicode.ToLower(r))
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

// rustReturnExpr drops one layer of redundant outer parens for block returns
// (avoids rustc unused_parens warnings while keeping nested ops parenthesized).
func rustReturnExpr(s string) string {
	s = strings.TrimSpace(s)
	if len(s) < 2 || s[0] != '(' || s[len(s)-1] != ')' {
		return s
	}
	depth := 0
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 && i != len(s)-1 {
				return s // outer pair doesn't wrap the whole expr
			}
		}
	}
	if depth == 0 {
		return strings.TrimSpace(s[1 : len(s)-1])
	}
	return s
}

// litToRust renders Init-time literals (and simple bound consts).
func (cg *CodeGen) litToRust(e tla.Expr) string {
	switch v := e.(type) {
	case tla.BoolLit:
		if v.Val {
			return "true"
		}
		return "false"
	case tla.IntLit:
		return fmt.Sprintf("%d", v.Val)
	case tla.StrLit:
		return fmt.Sprintf("String::from(%q)", v.Val)
	case nil:
		return "Default::default()"
	default:
		// fall through to general expr with dummy recv
		return cg.exprToRust(e, "/*init*/", false)
	}
}

// exprToRust lowers a scalar TLA expression. recv is "self" or "pre".
// asValue: when true, string vars use clone (for owned field construction).
func (cg *CodeGen) exprToRust(e tla.Expr, recv string, asValue bool) string {
	switch v := e.(type) {
	case tla.BoolLit:
		if v.Val {
			return "true"
		}
		return "false"
	case tla.IntLit:
		return fmt.Sprintf("%d", v.Val)
	case tla.StrLit:
		if asValue {
			return fmt.Sprintf("String::from(%q)", v.Val)
		}
		return fmt.Sprintf("%q", v.Val)
	case tla.VarRef:
		if g, ok := cg.constRust(v.Name); ok {
			return g
		}
		field := rustField(v.Name)
		ref := recv + "." + field
		if asValue && cg.inferType(v.Name) == "string" {
			return ref + ".clone()"
		}
		return ref
	case tla.UnaryOp:
		if v.Op == "~" {
			return "!(" + cg.exprToRust(v.Operand, recv, false) + ")"
		}
		return "/* unsupported unary " + v.Op + " */ true"
	case tla.BinOp:
		lhs := cg.exprToRust(v.Lhs, recv, false)
		rhs := cg.exprToRust(v.Rhs, recv, false)
		switch v.Op {
		case "=":
			return fmt.Sprintf("(%s == %s)", lhs, rhs)
		case "/=":
			return fmt.Sprintf("(%s != %s)", lhs, rhs)
		case "/\\":
			return fmt.Sprintf("(%s && %s)", lhs, rhs)
		case "\\/":
			return fmt.Sprintf("(%s || %s)", lhs, rhs)
		case "+":
			return fmt.Sprintf("(%s + %s)", lhs, rhs)
		case "-":
			return fmt.Sprintf("(%s - %s)", lhs, rhs)
		case "*":
			return fmt.Sprintf("(%s * %s)", lhs, rhs)
		case ">":
			return fmt.Sprintf("(%s > %s)", lhs, rhs)
		case "<":
			return fmt.Sprintf("(%s < %s)", lhs, rhs)
		case ">=":
			return fmt.Sprintf("(%s >= %s)", lhs, rhs)
		case "<=":
			return fmt.Sprintf("(%s <= %s)", lhs, rhs)
		case "=>":
			return fmt.Sprintf("(!(%s) || (%s))", lhs, rhs)
		case "\\in":
			// phase \in {"clamped", "done"} → (phase == "clamped" || phase == "done")
			if sl, ok := v.Rhs.(tla.SetLit); ok {
				var parts []string
				for _, el := range sl.Elems {
					parts = append(parts, fmt.Sprintf("(%s == %s)", lhs, cg.exprToRust(el, recv, false)))
				}
				if len(parts) == 0 {
					return "false"
				}
				return "(" + strings.Join(parts, " || ") + ")"
			}
			return fmt.Sprintf("/* unsupported \\in */ true")
		case "\\notin":
			if sl, ok := v.Rhs.(tla.SetLit); ok {
				var parts []string
				for _, el := range sl.Elems {
					parts = append(parts, fmt.Sprintf("(%s != %s)", lhs, cg.exprToRust(el, recv, false)))
				}
				if len(parts) == 0 {
					return "true"
				}
				return "(" + strings.Join(parts, " && ") + ")"
			}
			return fmt.Sprintf("/* unsupported \\notin */ true")
		default:
			return fmt.Sprintf("/* unsupported op %s */ true", v.Op)
		}
	case tla.IfExpr:
		// Always parenthesize if-expressions so `if c { a } else { b } + 1`
		// parses as intended. Cond/then/else drop redundant outer layers.
		return fmt.Sprintf(
			"(if %s { %s } else { %s })",
			rustReturnExpr(cg.exprToRust(v.Cond, recv, false)),
			rustReturnExpr(cg.exprToRust(v.Then, recv, asValue)),
			rustReturnExpr(cg.exprToRust(v.Else, recv, asValue)),
		)
	default:
		return "/* unsupported expr */ true"
	}
}

func (cg *CodeGen) constRust(name string) (string, bool) {
	isConst := false
	for _, c := range cg.Spec.Constants {
		if c == name {
			isConst = true
			break
		}
	}
	if !isConst {
		return "", false
	}
	if cg.Spec.ConstBindings != nil {
		if bound, ok := cg.Spec.ConstBindings[name]; ok {
			return cg.exprToRust(bound, "self", false), true
		}
	}
	// Unbound non-set CONSTANT: model value as string (rare in decision cores).
	return fmt.Sprintf("%q", name), true
}
