load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "receiver",
    srcs = ["receiver.go"],
    importpath = "github.com/stefanpenner/otel-explorer/pkg/ingest/receiver",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/ingest/otlpfile",
        "@io_opentelemetry_go_otel_sdk//trace",
    ],
)

go_test(
    name = "receiver_test",
    srcs = [
        "receiver_fuzz_test.go",
        "receiver_test.go",
    ],
    embed = [":receiver"],
    deps = [
        "@io_opentelemetry_go_proto_otlp//trace/v1:trace",
        "@org_golang_google_protobuf//proto",
    ],
)
