// Code generated by specgen from specs/gha-lifecycle/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/gha-lifecycle/decision/Decision.tla
// Regenerate: specgen -const Bug=FALSE -o pkg/analyzer/ghalifecyclespec -p ghalifecyclespec specs/gha-lifecycle/decision/Decision.tla
//
// Edit the spec, not this file: change the .tla above and re-run the command.

package ghalifecyclespec

// State mirrors the TLA+ VARIABLES.
type State struct {
	HasCompletedAt bool
	Conclusion     string
	CountedPending bool
	CountedFailed  bool
	QueueCounted   bool
}

// Init returns the initial state from the TLA+ Init predicate.
func Init() State {
	s := State{
		HasCompletedAt: false,
		Conclusion:     "failure",
		CountedPending: false,
		CountedFailed:  false,
		QueueCounted:   false,
	}
	return s
}

// CanClassifyPending is the guard for the ClassifyPending action.
func (s State) CanClassifyPending() bool {
	return !(s.HasCompletedAt) && !(s.CountedPending)
}

// ClassifyPending applies the ClassifyPending action, returning a new state.
func (s State) ClassifyPending() State {
	s.CountedPending = true
	return s
}

// CanClassifyFailed is the guard for the ClassifyFailed action.
func (s State) CanClassifyFailed() bool {
	return false || s.HasCompletedAt && s.Conclusion == "failure" || s.Conclusion == "timed_out" && !(s.CountedFailed)
}

// ClassifyFailed applies the ClassifyFailed action, returning a new state.
func (s State) ClassifyFailed() State {
	s.CountedFailed = true
	return s
}

// CanClassifyQueue is the guard for the ClassifyQueue action.
func (s State) CanClassifyQueue() bool {
	return false || s.HasCompletedAt && !(s.QueueCounted)
}

// ClassifyQueue applies the ClassifyQueue action, returning a new state.
func (s State) ClassifyQueue() State {
	s.QueueCounted = true
	return s
}

// CanReset is the guard for the Reset action.
func (s State) CanReset() bool {
	return true
}

// Reset applies the Reset action, returning a new state.
func (s State) Reset() State {
	pre := s
	s.CountedPending = false
	s.CountedFailed = false
	s.QueueCounted = false
	s.HasCompletedAt = true
	s.Conclusion = specgenIf(pre.Conclusion == "failure", "timed_out", specgenIf(pre.Conclusion == "timed_out", "success", "failure"))
	return s
}

// EnabledActions returns the names of actions whose guards are satisfied.
func (s State) EnabledActions() []string {
	var out []string
	if s.CanClassifyPending() {
		out = append(out, "ClassifyPending")
	}
	if s.CanClassifyFailed() {
		out = append(out, "ClassifyFailed")
	}
	if s.CanClassifyQueue() {
		out = append(out, "ClassifyQueue")
	}
	if s.CanReset() {
		out = append(out, "Reset")
	}
	return out
}

// --- Pure operators (no primed vars; not actions) ---

// PendingNeverFailed is the pure TLA+ operator PendingNeverFailed.
func (s State) PendingNeverFailed() bool {
	return !(s.CountedPending && s.CountedFailed)
}

// QueueOnlyNotPending is the pure TLA+ operator QueueOnlyNotPending.
func (s State) QueueOnlyNotPending() bool {
	return (!(s.QueueCounted) || (s.HasCompletedAt))
}

// PurePredicate is a named pure decision gate (no state change).
type PurePredicate struct {
	Name  string
	Check func(State) bool
}

// PurePredicates returns every pure operator emitted for this module.
func PurePredicates() []PurePredicate {
	return []PurePredicate{
		{Name: "PendingNeverFailed", Check: State.PendingNeverFailed},
		{Name: "QueueOnlyNotPending", Check: State.QueueOnlyNotPending},
	}
}

// --- Trace emission for conformance checking ---

// TraceEntry is a single recorded transition for conformance validation.
// Arg and Consts are empty/nil for a named action (PATH A); for a
// Step-dispatch spec (PATH B), Arg carries the input value Step was called
// with, and Consts carries the value of every free CONSTANT parameter (e.g.
// HasSel) — without it, a replayed trace couldn't reconstruct what Step
// actually saw whenever a free var varies between calls.
type TraceEntry struct {
	Action string          `json:"action"`
	Arg    string          `json:"arg,omitempty"`
	Args   []string        `json:"args,omitempty"`
	Consts map[string]bool `json:"consts,omitempty"`
	Pre    State           `json:"pre"`
	Post   State           `json:"post"`
}

// ApplyAction dispatches a named action, returning the new state.
// Panics on unknown action names.
func (s State) ApplyAction(name string) State {
	switch name {
	case "ClassifyPending":
		return s.ClassifyPending()
	case "ClassifyFailed":
		return s.ClassifyFailed()
	case "ClassifyQueue":
		return s.ClassifyQueue()
	case "Reset":
		return s.Reset()
	default:
		panic("unknown action: " + name)
	}
}

// Trace records a transition: applies the action and returns
// both the trace entry and the new state.
func (s State) Trace(action string) (TraceEntry, State) {
	pre := s
	post := s.ApplyAction(action)
	return TraceEntry{
		Action: action,
		Pre:    pre,
		Post:   post,
	}, post
}

// specgenIf evaluates a TLA+ IF/THEN/ELSE used as a value.
func specgenIf[T any](cond bool, then, els T) T {
	if cond {
		return then
	}
	return els
}
