load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "sample-eval_lib",
    srcs = ["main.go"],
    importpath = "github.com/stefanpenner/otel-explorer/cmd/sample-eval",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/analyzer",
        "//pkg/githubapi",
    ],
)

go_binary(
    name = "sample-eval",
    embed = [":sample-eval_lib"],
    visibility = ["//visibility:public"],
)
