// Code generated by specgen from specs/span-tree/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/span-tree/decision/Decision.tla
// Regenerate: specgen -const Bug=FALSE -o pkg/analyzer/spantreespec -p spantreespec specs/span-tree/decision/Decision.tla
//
// Edit the spec, not this file: change the .tla above and re-run the command.

package spantreespec

// State mirrors the TLA+ VARIABLES.
type State struct {
	HaveAPI    bool
	HaveRunner bool
	Kept       string
	Done       bool
}

// Init returns the initial state from the TLA+ Init predicate.
func Init() State {
	s := State{
		HaveAPI:    false,
		HaveRunner: false,
		Kept:       "none",
		Done:       false,
	}
	return s
}

// CanSeeAPI is the guard for the SeeAPI action.
func (s State) CanSeeAPI() bool {
	return !(s.Done) && !(s.HaveAPI)
}

// SeeAPI applies the SeeAPI action, returning a new state.
func (s State) SeeAPI() State {
	s.HaveAPI = true
	return s
}

// CanSeeRunner is the guard for the SeeRunner action.
func (s State) CanSeeRunner() bool {
	return !(s.Done) && !(s.HaveRunner)
}

// SeeRunner applies the SeeRunner action, returning a new state.
func (s State) SeeRunner() State {
	s.HaveRunner = true
	return s
}

// CanDedupChoose is the guard for the DedupChoose action.
func (s State) CanDedupChoose() bool {
	return !(s.Done) && specgenIf(s.HaveAPI, true, s.HaveRunner)
}

// DedupChoose applies the DedupChoose action, returning a new state.
func (s State) DedupChoose() State {
	pre := s
	s.Done = true
	s.Kept = specgenIf(pre.HaveAPI && pre.HaveRunner, "runner", specgenIf(pre.HaveRunner, "runner", "api"))
	return s
}

// CanDedupBug is the guard for the DedupBug action.
func (s State) CanDedupBug() bool {
	return false && !(s.Done) && s.HaveAPI && s.HaveRunner
}

// DedupBug applies the DedupBug action, returning a new state.
func (s State) DedupBug() State {
	s.Done = true
	s.Kept = "api"
	return s
}

// CanTerminating is the guard for the Terminating action.
func (s State) CanTerminating() bool {
	return s.Done
}

// Terminating applies the Terminating action, returning a new state.
func (s State) Terminating() State {
	return s
}

// EnabledActions returns the names of actions whose guards are satisfied.
func (s State) EnabledActions() []string {
	var out []string
	if s.CanSeeAPI() {
		out = append(out, "SeeAPI")
	}
	if s.CanSeeRunner() {
		out = append(out, "SeeRunner")
	}
	if s.CanDedupChoose() {
		out = append(out, "DedupChoose")
	}
	if s.CanDedupBug() {
		out = append(out, "DedupBug")
	}
	if s.CanTerminating() {
		out = append(out, "Terminating")
	}
	return out
}

// --- Pure operators (no primed vars; not actions) ---

// Inv_RunnerWins is the pure TLA+ operator Inv_RunnerWins.
func (s State) Inv_RunnerWins() bool {
	return (!(s.Done && s.HaveAPI && s.HaveRunner) || (s.Kept == "runner"))
}

// --- Trace emission for conformance checking ---

// TraceEntry is a single recorded transition for conformance validation.
// Arg and Consts are empty/nil for a named action (PATH A); for a
// Step-dispatch spec (PATH B), Arg carries the input value Step was called
// with, and Consts carries the value of every free CONSTANT parameter (e.g.
// HasSel) — without it, a replayed trace couldn't reconstruct what Step
// actually saw whenever a free var varies between calls.
type TraceEntry struct {
	Action string          `json:"action"`
	Arg    string          `json:"arg,omitempty"`
	Args   []string        `json:"args,omitempty"`
	Consts map[string]bool `json:"consts,omitempty"`
	Pre    State           `json:"pre"`
	Post   State           `json:"post"`
}

// ApplyAction dispatches a named action, returning the new state.
// Panics on unknown action names.
func (s State) ApplyAction(name string) State {
	switch name {
	case "SeeAPI":
		return s.SeeAPI()
	case "SeeRunner":
		return s.SeeRunner()
	case "DedupChoose":
		return s.DedupChoose()
	case "DedupBug":
		return s.DedupBug()
	case "Terminating":
		return s.Terminating()
	default:
		panic("unknown action: " + name)
	}
}

// Trace records a transition: applies the action and returns
// both the trace entry and the new state.
func (s State) Trace(action string) (TraceEntry, State) {
	pre := s
	post := s.ApplyAction(action)
	return TraceEntry{
		Action: action,
		Pre:    pre,
		Post:   post,
	}, post
}

// specgenIf evaluates a TLA+ IF/THEN/ELSE used as a value.
func specgenIf[T any](cond bool, then, els T) T {
	if cond {
		return then
	}
	return els
}
