// Code generated by specgen from specs/timing-clamp/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/timing-clamp/decision/Decision.tla
// Regenerate: specgen -const Tmax=4 -const Bug=FALSE -o pkg/analyzer/timingclampspec -p timingclampspec specs/timing-clamp/decision/Decision.tla
//
// Edit the spec, not this file: change the .tla above and re-run the command.

package timingclampspec

// State mirrors the TLA+ VARIABLES.
type State struct {
	Phase       string
	Start       int64
	End         int64
	ParentStart int64
	ParentEnd   int64
	OutStart    int64
	OutEnd      int64
}

// Init returns the initial state from the TLA+ Init predicate.
func Init() State {
	s := State{
		Phase:       "init",
		Start:       2,
		End:         4,
		ParentStart: 1,
		ParentEnd:   3,
		OutStart:    0,
		OutEnd:      0,
	}
	return s
}

// CanSetHostile is the guard for the SetHostile action.
func (s State) CanSetHostile() bool {
	return s.Phase == "init"
}

// SetHostile applies the SetHostile action, returning a new state.
func (s State) SetHostile() State {
	s.Start = 0
	s.End = 4
	s.ParentStart = 2
	s.ParentEnd = 3
	return s
}

// CanDoClamp is the guard for the DoClamp action.
func (s State) CanDoClamp() bool {
	return s.Phase == "init" && !(false)
}

// DoClamp applies the DoClamp action, returning a new state.
func (s State) DoClamp() State {
	pre := s
	s.Phase = "clamped"
	s.OutStart = specgenIf(pre.Start < pre.ParentStart, pre.ParentStart, specgenIf(pre.Start > specgenIf(pre.ParentEnd <= pre.ParentStart, pre.ParentStart+1, pre.ParentEnd)-1, specgenIf(pre.ParentEnd <= pre.ParentStart, pre.ParentStart+1, pre.ParentEnd)-1, pre.Start))
	s.OutEnd = specgenIf(specgenIf(pre.End > specgenIf(pre.ParentEnd <= pre.ParentStart, pre.ParentStart+1, pre.ParentEnd), specgenIf(pre.ParentEnd <= pre.ParentStart, pre.ParentStart+1, pre.ParentEnd), pre.End) < specgenIf(pre.Start < pre.ParentStart, pre.ParentStart, specgenIf(pre.Start > specgenIf(pre.ParentEnd <= pre.ParentStart, pre.ParentStart+1, pre.ParentEnd)-1, specgenIf(pre.ParentEnd <= pre.ParentStart, pre.ParentStart+1, pre.ParentEnd)-1, pre.Start))+1, specgenIf(pre.Start < pre.ParentStart, pre.ParentStart, specgenIf(pre.Start > specgenIf(pre.ParentEnd <= pre.ParentStart, pre.ParentStart+1, pre.ParentEnd)-1, specgenIf(pre.ParentEnd <= pre.ParentStart, pre.ParentStart+1, pre.ParentEnd)-1, pre.Start))+1, specgenIf(pre.End > specgenIf(pre.ParentEnd <= pre.ParentStart, pre.ParentStart+1, pre.ParentEnd), specgenIf(pre.ParentEnd <= pre.ParentStart, pre.ParentStart+1, pre.ParentEnd), pre.End))
	return s
}

// CanBugPassthrough is the guard for the BugPassthrough action.
func (s State) CanBugPassthrough() bool {
	return s.Phase == "init" && false
}

// BugPassthrough applies the BugPassthrough action, returning a new state.
func (s State) BugPassthrough() State {
	pre := s
	s.Phase = "clamped"
	s.OutStart = pre.Start
	s.OutEnd = pre.End
	return s
}

// CanFinish is the guard for the Finish action.
func (s State) CanFinish() bool {
	return s.Phase == "clamped"
}

// Finish applies the Finish action, returning a new state.
func (s State) Finish() State {
	s.Phase = "done"
	return s
}

// EnabledActions returns the names of actions whose guards are satisfied.
func (s State) EnabledActions() []string {
	var out []string
	if s.CanSetHostile() {
		out = append(out, "SetHostile")
	}
	if s.CanDoClamp() {
		out = append(out, "DoClamp")
	}
	if s.CanBugPassthrough() {
		out = append(out, "BugPassthrough")
	}
	if s.CanFinish() {
		out = append(out, "Finish")
	}
	return out
}

// --- Trace emission for conformance checking ---

// TraceEntry is a single recorded transition for conformance validation.
// Arg and Consts are empty/nil for a named action (PATH A); for a
// Step-dispatch spec (PATH B), Arg carries the input value Step was called
// with, and Consts carries the value of every free CONSTANT parameter (e.g.
// HasSel) — without it, a replayed trace couldn't reconstruct what Step
// actually saw whenever a free var varies between calls.
type TraceEntry struct {
	Action string          `json:"action"`
	Arg    string          `json:"arg,omitempty"`
	Args   []string        `json:"args,omitempty"`
	Consts map[string]bool `json:"consts,omitempty"`
	Pre    State           `json:"pre"`
	Post   State           `json:"post"`
}

// ApplyAction dispatches a named action, returning the new state.
// Panics on unknown action names.
func (s State) ApplyAction(name string) State {
	switch name {
	case "SetHostile":
		return s.SetHostile()
	case "DoClamp":
		return s.DoClamp()
	case "BugPassthrough":
		return s.BugPassthrough()
	case "Finish":
		return s.Finish()
	default:
		panic("unknown action: " + name)
	}
}

// Trace records a transition: applies the action and returns
// both the trace entry and the new state.
func (s State) Trace(action string) (TraceEntry, State) {
	pre := s
	post := s.ApplyAction(action)
	return TraceEntry{
		Action: action,
		Pre:    pre,
		Post:   post,
	}, post
}

// specgenIf evaluates a TLA+ IF/THEN/ELSE used as a value.
func specgenIf[T any](cond bool, then, els T) T {
	if cond {
		return then
	}
	return els
}
