// Code generated by specgen — DO NOT EDIT.

package timingclampspec

import (
	"fmt"
	"testing"
)

func TestInit(t *testing.T) {
	s := Init()
	if s.Phase != string("init") {
		t.Errorf("Phase = %v, want %v", s.Phase, string("init"))
	}
	if s.Start != int64(2) {
		t.Errorf("Start = %v, want %v", s.Start, int64(2))
	}
	if s.End != int64(4) {
		t.Errorf("End = %v, want %v", s.End, int64(4))
	}
	if s.ParentStart != int64(1) {
		t.Errorf("ParentStart = %v, want %v", s.ParentStart, int64(1))
	}
	if s.ParentEnd != int64(3) {
		t.Errorf("ParentEnd = %v, want %v", s.ParentEnd, int64(3))
	}
	if s.OutStart != int64(0) {
		t.Errorf("OutStart = %v, want %v", s.OutStart, int64(0))
	}
	if s.OutEnd != int64(0) {
		t.Errorf("OutEnd = %v, want %v", s.OutEnd, int64(0))
	}
}

// TestBFSReachability walks the state space from Init, applying every
// enabled action. Verifies no transition panics and all states are reachable.
func TestBFSReachability(t *testing.T) {
	seen := map[string]bool{}
	queue := []State{Init()}
	maxStates := 10000

	for len(queue) > 0 && len(seen) < maxStates {
		s := queue[0]
		queue = queue[1:]
		key := fmt.Sprintf("%+v", s)
		if seen[key] {
			continue
		}
		seen[key] = true

		for _, action := range s.EnabledActions() {
			next := s.ApplyAction(action)
			queue = append(queue, next)
		}
	}

	if len(seen) == 0 {
		t.Fatal("no reachable states")
	}
	t.Logf("explored %d reachable states", len(seen))
}

// TestPurePredicates evaluates every pure operator on Init.
// Ensures the registry is non-empty and methods do not panic.
func TestPurePredicates(t *testing.T) {
	s := Init()
	preds := PurePredicates()
	if len(preds) == 0 {
		t.Fatal("PurePredicates empty")
	}
	for _, p := range preds {
		t.Run(p.Name, func(t *testing.T) {
			_ = p.Check(s) // must not panic
		})
	}
}
