// Code generated by specgen — DO NOT EDIT.

package timingclampspec

import (
	"fmt"
	"testing"
)

func TestInit(t *testing.T) {
	s := Init()
	if s.Phase != string("init") {
		t.Errorf("Phase = %v, want %v", s.Phase, string("init"))
	}
	if s.Start != int64(2) {
		t.Errorf("Start = %v, want %v", s.Start, int64(2))
	}
	if s.End != int64(4) {
		t.Errorf("End = %v, want %v", s.End, int64(4))
	}
	if s.ParentStart != int64(1) {
		t.Errorf("ParentStart = %v, want %v", s.ParentStart, int64(1))
	}
	if s.ParentEnd != int64(3) {
		t.Errorf("ParentEnd = %v, want %v", s.ParentEnd, int64(3))
	}
	if s.OutStart != int64(0) {
		t.Errorf("OutStart = %v, want %v", s.OutStart, int64(0))
	}
	if s.OutEnd != int64(0) {
		t.Errorf("OutEnd = %v, want %v", s.OutEnd, int64(0))
	}
}

// TestBFSReachability walks the state space from Init, applying every
// enabled action. Verifies no transition panics and all states are reachable.
func TestBFSReachability(t *testing.T) {
	seen := map[string]bool{}
	queue := []State{Init()}
	maxStates := 10000

	for len(queue) > 0 && len(seen) < maxStates {
		s := queue[0]
		queue = queue[1:]
		key := fmt.Sprintf("%+v", s)
		if seen[key] {
			continue
		}
		seen[key] = true

		for _, action := range s.EnabledActions() {
			next := s.ApplyAction(action)
			queue = append(queue, next)
		}
	}

	if len(seen) == 0 {
		t.Fatal("no reachable states")
	}
	t.Logf("explored %d reachable states", len(seen))
}

// TestPurePredicates is the generated pure-gate dual stub.
// Names come from Decision.tla (SSOT); dual package tests cover production wiring.
func TestPurePredicates(t *testing.T) {
	want := []string{
		"ClampedOrdered",
		"ClampedContained",
	}
	s := Init()
	preds := PurePredicates()
	if len(preds) != len(want) {
		t.Fatalf("PurePredicates len=%d want %d", len(preds), len(want))
	}
	got := make(map[string]bool, len(preds))
	for _, p := range preds {
		if p.Name == "" {
			t.Fatal("empty PurePredicate.Name")
		}
		if got[p.Name] {
			t.Fatalf("duplicate pure name %q", p.Name)
		}
		got[p.Name] = true
		t.Run(p.Name, func(t *testing.T) {
			_ = p.Check(s) // must not panic
		})
	}
	for _, name := range want {
		if !got[name] {
			t.Fatalf("missing pure %q in PurePredicates()", name)
		}
	}
}
