// Code generated by specgen from specs/gha-lifecycle/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/gha-lifecycle/decision/Decision.tla
// Regenerate: bazel run //tools/decision:update
//
// Edit the .tla, not this file. Language: Rust (PATH A decision core).
// Package/module hint: ghalifecyclespec

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct State {
	pub has_completed_at: bool,
	pub conclusion: String,
	pub counted_pending: bool,
	pub counted_failed: bool,
	pub queue_counted: bool,
}

impl State {
	/// Initial state from the TLA+ Init predicate.
	pub fn init() -> Self {
		Self {
			has_completed_at: false,
			conclusion: String::from("failure"),
			counted_pending: false,
			counted_failed: false,
			queue_counted: false,
		}
	}

	/// Guard for action ClassifyPending.
	pub fn can_classify_pending(&self) -> bool {
		!(self.has_completed_at) && !(self.counted_pending)
	}

	/// Apply action ClassifyPending (consuming self — pure transition).
	pub fn classify_pending(self) -> Self {
		let pre = self;
		Self {
			counted_pending: true,
			has_completed_at: pre.has_completed_at,
			conclusion: pre.conclusion,
			counted_failed: pre.counted_failed,
			queue_counted: pre.queue_counted,
		}
	}

	/// Guard for action ClassifyFailed.
	pub fn can_classify_failed(&self) -> bool {
		((false || self.has_completed_at) && ((self.conclusion == "failure") || (self.conclusion == "timed_out"))) && !(self.counted_failed)
	}

	/// Apply action ClassifyFailed (consuming self — pure transition).
	pub fn classify_failed(self) -> Self {
		let pre = self;
		Self {
			counted_failed: true,
			has_completed_at: pre.has_completed_at,
			conclusion: pre.conclusion,
			counted_pending: pre.counted_pending,
			queue_counted: pre.queue_counted,
		}
	}

	/// Guard for action ClassifyQueue.
	pub fn can_classify_queue(&self) -> bool {
		(false || self.has_completed_at) && !(self.queue_counted)
	}

	/// Apply action ClassifyQueue (consuming self — pure transition).
	pub fn classify_queue(self) -> Self {
		let pre = self;
		Self {
			queue_counted: true,
			has_completed_at: pre.has_completed_at,
			conclusion: pre.conclusion,
			counted_pending: pre.counted_pending,
			counted_failed: pre.counted_failed,
		}
	}

	/// Guard for action Reset.
	pub fn can_reset(&self) -> bool {
		true
	}

	/// Apply action Reset (consuming self — pure transition).
	pub fn reset(self) -> Self {
		let pre = self;
		Self {
			counted_pending: false,
			counted_failed: false,
			queue_counted: false,
			has_completed_at: true,
			conclusion: (if pre.conclusion == "failure" { String::from("timed_out") } else { if pre.conclusion == "timed_out" { String::from("success") } else { String::from("failure") } }),
		}
	}

	/// Names of actions whose guards hold.
	pub fn enabled_actions(&self) -> Vec<&'static str> {
		let mut out = Vec::new();
		if self.can_classify_pending() {
			out.push("ClassifyPending");
		}
		if self.can_classify_failed() {
			out.push("ClassifyFailed");
		}
		if self.can_classify_queue() {
			out.push("ClassifyQueue");
		}
		if self.can_reset() {
			out.push("Reset");
		}
		out
	}

	/// Apply a named action if its guard holds.
	pub fn apply_action(self, name: &str) -> Option<Self> {
		match name {
			"ClassifyPending" => {
				if self.can_classify_pending() {
					Some(self.classify_pending())
				} else {
					None
				}
			}
			"ClassifyFailed" => {
				if self.can_classify_failed() {
					Some(self.classify_failed())
				} else {
					None
				}
			}
			"ClassifyQueue" => {
				if self.can_classify_queue() {
					Some(self.classify_queue())
				} else {
					None
				}
			}
			"Reset" => {
				if self.can_reset() {
					Some(self.reset())
				} else {
					None
				}
			}
			_ => None,
		}
	}
}

impl State {
	/// Pure TLA+ operator PendingNeverFailed.
	pub fn pending_never_failed(&self) -> bool {
		!((self.counted_pending && self.counted_failed))
	}

	/// Pure TLA+ operator QueueOnlyNotPending.
	pub fn queue_only_not_pending(&self) -> bool {
		!(self.queue_counted) || (self.has_completed_at)
	}

}

/// Named pure predicates for dual/CI enumeration.
pub struct PurePredicate {
	pub name: &'static str,
	pub check: fn(&State) -> bool,
}

/// Every pure operator emitted for this module.
pub const PURE_PREDICATES: &[PurePredicate] = &[
	PurePredicate { name: "PendingNeverFailed", check: State::pending_never_failed },
	PurePredicate { name: "QueueOnlyNotPending", check: State::queue_only_not_pending },
];

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn init_ok() {
		let s = State::init();
		let _ = s.enabled_actions();
	}

	#[test]
	fn pure_predicates_no_panic() {
		let s = State::init();
		assert_eq!(PURE_PREDICATES.len(), 2);
		for p in PURE_PREDICATES {
			let _ = (p.check)(&s);
		}
	}
}
