// Code generated by specgen from specs/log-groups/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/log-groups/decision/Decision.tla
// Regenerate: bazel run //tools/decision:update
//
// Edit the .tla, not this file. Language: Rust (PATH A decision core).
// Package/module hint: loggroupsspec

#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
pub struct State {
	pub depth: i64,
}

impl State {
	/// Initial state from the TLA+ Init predicate.
	pub fn init() -> Self {
		Self {
			depth: 0,
		}
	}

	/// Guard for action Open.
	pub fn can_open(&self) -> bool {
		(self.depth >= 0) && (self.depth < 3)
	}

	/// Apply action Open (consuming self — pure transition).
	pub fn open(self) -> Self {
		let pre = self;
		Self {
			depth: (pre.depth + 1),
		}
	}

	/// Guard for action Close.
	pub fn can_close(&self) -> bool {
		self.depth > 0
	}

	/// Apply action Close (consuming self — pure transition).
	pub fn close(self) -> Self {
		let pre = self;
		Self {
			depth: (pre.depth - 1),
		}
	}

	/// Guard for action CloseBug.
	pub fn can_close_bug(&self) -> bool {
		false && (self.depth == 0)
	}

	/// Apply action CloseBug (consuming self — pure transition).
	pub fn close_bug(self) -> Self {
		let pre = self;
		Self {
			depth: (pre.depth - 1),
		}
	}

	/// Guard for action Terminating.
	pub fn can_terminating(&self) -> bool {
		true
	}

	/// Apply action Terminating (consuming self — pure transition).
	pub fn terminating(self) -> Self {
		let pre = self;
		Self {
			depth: pre.depth,
		}
	}

	/// Names of actions whose guards hold.
	pub fn enabled_actions(&self) -> Vec<&'static str> {
		let mut out = Vec::new();
		if self.can_open() {
			out.push("Open");
		}
		if self.can_close() {
			out.push("Close");
		}
		if self.can_close_bug() {
			out.push("CloseBug");
		}
		if self.can_terminating() {
			out.push("Terminating");
		}
		out
	}

	/// Apply a named action if its guard holds.
	pub fn apply_action(self, name: &str) -> Option<Self> {
		match name {
			"Open" => {
				if self.can_open() {
					Some(self.open())
				} else {
					None
				}
			}
			"Close" => {
				if self.can_close() {
					Some(self.close())
				} else {
					None
				}
			}
			"CloseBug" => {
				if self.can_close_bug() {
					Some(self.close_bug())
				} else {
					None
				}
			}
			"Terminating" => {
				if self.can_terminating() {
					Some(self.terminating())
				} else {
					None
				}
			}
			_ => None,
		}
	}
}

impl State {
	/// Pure TLA+ operator Inv_DepthNonNeg.
	pub fn inv_depth_non_neg(&self) -> bool {
		self.depth >= 0
	}

}

/// Named pure predicates for dual/CI enumeration.
pub struct PurePredicate {
	pub name: &'static str,
	pub check: fn(&State) -> bool,
}

/// Every pure operator emitted for this module.
pub const PURE_PREDICATES: &[PurePredicate] = &[
	PurePredicate { name: "Inv_DepthNonNeg", check: State::inv_depth_non_neg },
];

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn init_ok() {
		let s = State::init();
		let _ = s.enabled_actions();
	}

	#[test]
	fn pure_predicates_no_panic() {
		let s = State::init();
		assert_eq!(PURE_PREDICATES.len(), 1);
		for p in PURE_PREDICATES {
			let _ = (p.check)(&s);
		}
	}
}
