// Code generated by specgen from specs/rate-limit/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/rate-limit/decision/Decision.tla
// Regenerate: bazel run //tools/decision:update
//
// Edit the .tla, not this file. Language: Rust (PATH A decision core).
// Package/module hint: ratelimitspec

#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
pub struct State {
	pub remaining: i64,
	pub sleeping: bool,
	pub clock: i64,
	pub reset_at: i64,
	pub sent_while_exhausted: bool,
}

impl State {
	/// Initial state from the TLA+ Init predicate.
	pub fn init() -> Self {
		Self {
			remaining: 2,
			sleeping: false,
			clock: 0,
			reset_at: 0,
			sent_while_exhausted: false,
		}
	}

	/// Guard for action LearnExhausted.
	pub fn can_learn_exhausted(&self) -> bool {
		(self.remaining > 0) && (self.clock < 3)
	}

	/// Apply action LearnExhausted (consuming self — pure transition).
	pub fn learn_exhausted(self) -> Self {
		let pre = self;
		Self {
			remaining: 0,
			reset_at: (pre.clock + 1),
			sleeping: pre.sleeping,
			clock: pre.clock,
			sent_while_exhausted: pre.sent_while_exhausted,
		}
	}

	/// Guard for action StartSleep.
	pub fn can_start_sleep(&self) -> bool {
		(((self.remaining == 0) && !(self.sleeping)) && (self.clock < self.reset_at)) && (self.reset_at > 0)
	}

	/// Apply action StartSleep (consuming self — pure transition).
	pub fn start_sleep(self) -> Self {
		let pre = self;
		Self {
			sleeping: true,
			remaining: pre.remaining,
			clock: pre.clock,
			reset_at: pre.reset_at,
			sent_while_exhausted: pre.sent_while_exhausted,
		}
	}

	/// Guard for action WakeRecheckSend.
	pub fn can_wake_recheck_send(&self) -> bool {
		self.sleeping && !((((self.remaining == 0) && (self.reset_at > 0)) && (self.clock < self.reset_at)))
	}

	/// Apply action WakeRecheckSend (consuming self — pure transition).
	pub fn wake_recheck_send(self) -> Self {
		let pre = self;
		Self {
			sleeping: false,
			remaining: 2,
			clock: pre.clock,
			reset_at: pre.reset_at,
			sent_while_exhausted: pre.sent_while_exhausted,
		}
	}

	/// Guard for action WakeRecheckResleep.
	pub fn can_wake_recheck_resleep(&self) -> bool {
		(((!(false) && self.sleeping) && (self.remaining == 0)) && (self.reset_at > 0)) && (self.clock < self.reset_at)
	}

	/// Apply action WakeRecheckResleep (consuming self — pure transition).
	pub fn wake_recheck_resleep(self) -> Self {
		let pre = self;
		Self {
			remaining: pre.remaining,
			sleeping: pre.sleeping,
			clock: pre.clock,
			reset_at: pre.reset_at,
			sent_while_exhausted: pre.sent_while_exhausted,
		}
	}

	/// Guard for action WakeBugSend.
	pub fn can_wake_bug_send(&self) -> bool {
		false && self.sleeping
	}

	/// Apply action WakeBugSend (consuming self — pure transition).
	pub fn wake_bug_send(self) -> Self {
		let pre = self;
		Self {
			sleeping: false,
			sent_while_exhausted: (((pre.remaining == 0) && (pre.reset_at > 0)) && (pre.clock < pre.reset_at)),
			remaining: (if ((pre.remaining == 0) && (pre.reset_at > 0)) && (pre.clock < pre.reset_at) { pre.remaining } else { 2 }),
			clock: pre.clock,
			reset_at: pre.reset_at,
		}
	}

	/// Guard for action Tick.
	pub fn can_tick(&self) -> bool {
		self.clock < 3
	}

	/// Apply action Tick (consuming self — pure transition).
	pub fn tick(self) -> Self {
		let pre = self;
		Self {
			clock: (pre.clock + 1),
			remaining: (if ((pre.remaining == 0) && (pre.reset_at > 0)) && ((pre.clock + 1) >= pre.reset_at) { 2 } else { pre.remaining }),
			sleeping: pre.sleeping,
			reset_at: pre.reset_at,
			sent_while_exhausted: pre.sent_while_exhausted,
		}
	}

	/// Guard for action SendOk.
	pub fn can_send_ok(&self) -> bool {
		(self.remaining > 0) && !(self.sleeping)
	}

	/// Apply action SendOk (consuming self — pure transition).
	pub fn send_ok(self) -> Self {
		let pre = self;
		Self {
			remaining: (pre.remaining - 1),
			sleeping: pre.sleeping,
			clock: pre.clock,
			reset_at: pre.reset_at,
			sent_while_exhausted: pre.sent_while_exhausted,
		}
	}

	/// Names of actions whose guards hold.
	pub fn enabled_actions(&self) -> Vec<&'static str> {
		let mut out = Vec::new();
		if self.can_learn_exhausted() {
			out.push("LearnExhausted");
		}
		if self.can_start_sleep() {
			out.push("StartSleep");
		}
		if self.can_wake_recheck_send() {
			out.push("WakeRecheckSend");
		}
		if self.can_wake_recheck_resleep() {
			out.push("WakeRecheckResleep");
		}
		if self.can_wake_bug_send() {
			out.push("WakeBugSend");
		}
		if self.can_tick() {
			out.push("Tick");
		}
		if self.can_send_ok() {
			out.push("SendOk");
		}
		out
	}

	/// Apply a named action if its guard holds.
	pub fn apply_action(self, name: &str) -> Option<Self> {
		match name {
			"LearnExhausted" => {
				if self.can_learn_exhausted() {
					Some(self.learn_exhausted())
				} else {
					None
				}
			}
			"StartSleep" => {
				if self.can_start_sleep() {
					Some(self.start_sleep())
				} else {
					None
				}
			}
			"WakeRecheckSend" => {
				if self.can_wake_recheck_send() {
					Some(self.wake_recheck_send())
				} else {
					None
				}
			}
			"WakeRecheckResleep" => {
				if self.can_wake_recheck_resleep() {
					Some(self.wake_recheck_resleep())
				} else {
					None
				}
			}
			"WakeBugSend" => {
				if self.can_wake_bug_send() {
					Some(self.wake_bug_send())
				} else {
					None
				}
			}
			"Tick" => {
				if self.can_tick() {
					Some(self.tick())
				} else {
					None
				}
			}
			"SendOk" => {
				if self.can_send_ok() {
					Some(self.send_ok())
				} else {
					None
				}
			}
			_ => None,
		}
	}
}

impl State {
	/// Pure TLA+ operator WaitNeeded.
	pub fn wait_needed(&self) -> bool {
		((self.remaining == 0) && (self.reset_at > 0)) && (self.clock < self.reset_at)
	}

	/// Pure TLA+ operator NoSendWhileExhausted.
	pub fn no_send_while_exhausted(&self) -> bool {
		!(self.sent_while_exhausted)
	}

}

/// Named pure predicates for dual/CI enumeration.
pub struct PurePredicate {
	pub name: &'static str,
	pub check: fn(&State) -> bool,
}

/// Every pure operator emitted for this module.
pub const PURE_PREDICATES: &[PurePredicate] = &[
	PurePredicate { name: "WaitNeeded", check: State::wait_needed },
	PurePredicate { name: "NoSendWhileExhausted", check: State::no_send_while_exhausted },
];

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn init_ok() {
		let s = State::init();
		let _ = s.enabled_actions();
	}

	#[test]
	fn pure_predicates_no_panic() {
		let s = State::init();
		assert_eq!(PURE_PREDICATES.len(), 2);
		for p in PURE_PREDICATES {
			let _ = (p.check)(&s);
		}
	}
}
