// Code generated by specgen from specs/span-tree/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/span-tree/decision/Decision.tla
// Regenerate: bazel run //tools/decision:update
//
// Edit the .tla, not this file. Language: Rust (PATH A decision core).
// Package/module hint: spantreespec

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct State {
	pub have_api: bool,
	pub have_runner: bool,
	pub kept: String,
	pub done: bool,
}

impl State {
	/// Initial state from the TLA+ Init predicate.
	pub fn init() -> Self {
		Self {
			have_api: false,
			have_runner: false,
			kept: String::from("none"),
			done: false,
		}
	}

	/// Guard for action SeeAPI.
	pub fn can_see_api(&self) -> bool {
		!(self.done) && !(self.have_api)
	}

	/// Apply action SeeAPI (consuming self — pure transition).
	pub fn see_api(self) -> Self {
		let pre = self;
		Self {
			have_api: true,
			have_runner: pre.have_runner,
			kept: pre.kept,
			done: pre.done,
		}
	}

	/// Guard for action SeeRunner.
	pub fn can_see_runner(&self) -> bool {
		!(self.done) && !(self.have_runner)
	}

	/// Apply action SeeRunner (consuming self — pure transition).
	pub fn see_runner(self) -> Self {
		let pre = self;
		Self {
			have_runner: true,
			have_api: pre.have_api,
			kept: pre.kept,
			done: pre.done,
		}
	}

	/// Guard for action DedupChoose.
	pub fn can_dedup_choose(&self) -> bool {
		!(self.done) && (if self.have_api { true } else { self.have_runner })
	}

	/// Apply action DedupChoose (consuming self — pure transition).
	pub fn dedup_choose(self) -> Self {
		let pre = self;
		Self {
			done: true,
			kept: (if pre.have_api && pre.have_runner { String::from("runner") } else { if pre.have_runner { String::from("runner") } else { String::from("api") } }),
			have_api: pre.have_api,
			have_runner: pre.have_runner,
		}
	}

	/// Guard for action DedupBug.
	pub fn can_dedup_bug(&self) -> bool {
		((false && !(self.done)) && self.have_api) && self.have_runner
	}

	/// Apply action DedupBug (consuming self — pure transition).
	pub fn dedup_bug(self) -> Self {
		let pre = self;
		Self {
			done: true,
			kept: String::from("api"),
			have_api: pre.have_api,
			have_runner: pre.have_runner,
		}
	}

	/// Guard for action Terminating.
	pub fn can_terminating(&self) -> bool {
		self.done
	}

	/// Apply action Terminating (consuming self — pure transition).
	pub fn terminating(self) -> Self {
		let pre = self;
		Self {
			have_api: pre.have_api,
			have_runner: pre.have_runner,
			kept: pre.kept,
			done: pre.done,
		}
	}

	/// Names of actions whose guards hold.
	pub fn enabled_actions(&self) -> Vec<&'static str> {
		let mut out = Vec::new();
		if self.can_see_api() {
			out.push("SeeAPI");
		}
		if self.can_see_runner() {
			out.push("SeeRunner");
		}
		if self.can_dedup_choose() {
			out.push("DedupChoose");
		}
		if self.can_dedup_bug() {
			out.push("DedupBug");
		}
		if self.can_terminating() {
			out.push("Terminating");
		}
		out
	}

	/// Apply a named action if its guard holds.
	pub fn apply_action(self, name: &str) -> Option<Self> {
		match name {
			"SeeAPI" => {
				if self.can_see_api() {
					Some(self.see_api())
				} else {
					None
				}
			}
			"SeeRunner" => {
				if self.can_see_runner() {
					Some(self.see_runner())
				} else {
					None
				}
			}
			"DedupChoose" => {
				if self.can_dedup_choose() {
					Some(self.dedup_choose())
				} else {
					None
				}
			}
			"DedupBug" => {
				if self.can_dedup_bug() {
					Some(self.dedup_bug())
				} else {
					None
				}
			}
			"Terminating" => {
				if self.can_terminating() {
					Some(self.terminating())
				} else {
					None
				}
			}
			_ => None,
		}
	}
}

impl State {
	/// Pure TLA+ operator Inv_RunnerWins.
	pub fn inv_runner_wins(&self) -> bool {
		!(((self.done && self.have_api) && self.have_runner)) || ((self.kept == "runner"))
	}

}

/// Named pure predicates for dual/CI enumeration.
pub struct PurePredicate {
	pub name: &'static str,
	pub check: fn(&State) -> bool,
}

/// Every pure operator emitted for this module.
pub const PURE_PREDICATES: &[PurePredicate] = &[
	PurePredicate { name: "Inv_RunnerWins", check: State::inv_runner_wins },
];

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn init_ok() {
		let s = State::init();
		let _ = s.enabled_actions();
	}

	#[test]
	fn pure_predicates_no_panic() {
		let s = State::init();
		assert_eq!(PURE_PREDICATES.len(), 1);
		for p in PURE_PREDICATES {
			let _ = (p.check)(&s);
		}
	}
}
