// Code generated by specgen from specs/sync-bounds/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/sync-bounds/decision/Decision.tla
// Regenerate: bazel run //tools/decision:update
//
// Edit the .tla, not this file. Language: Rust (PATH A decision core).
// Package/module hint: syncboundsspec

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct State {
	pub phase: String,
	pub stored_attempt: i64,
	pub incoming_attempt: i64,
	pub accepted: bool,
}

impl State {
	/// Initial state from the TLA+ Init predicate.
	pub fn init() -> Self {
		Self {
			phase: String::from("empty"),
			stored_attempt: 0,
			incoming_attempt: 0,
			accepted: false,
		}
	}

	/// Guard for action Store1.
	pub fn can_store1(&self) -> bool {
		(self.phase == "empty") || (self.phase == "stored")
	}

	/// Apply action Store1 (consuming self — pure transition).
	pub fn store1(self) -> Self {
		let pre = self;
		Self {
			phase: String::from("stored"),
			stored_attempt: 1,
			incoming_attempt: pre.incoming_attempt,
			accepted: pre.accepted,
		}
	}

	/// Guard for action Store2.
	pub fn can_store2(&self) -> bool {
		(self.phase == "empty") || (self.phase == "stored")
	}

	/// Apply action Store2 (consuming self — pure transition).
	pub fn store2(self) -> Self {
		let pre = self;
		Self {
			phase: String::from("stored"),
			stored_attempt: 2,
			incoming_attempt: pre.incoming_attempt,
			accepted: pre.accepted,
		}
	}

	/// Guard for action Store3.
	pub fn can_store3(&self) -> bool {
		(self.phase == "empty") || (self.phase == "stored")
	}

	/// Apply action Store3 (consuming self — pure transition).
	pub fn store3(self) -> Self {
		let pre = self;
		Self {
			phase: String::from("stored"),
			stored_attempt: 3,
			incoming_attempt: pre.incoming_attempt,
			accepted: pre.accepted,
		}
	}

	/// Guard for action OfferNewer.
	pub fn can_offer_newer(&self) -> bool {
		(self.phase == "stored") && (self.stored_attempt > 0)
	}

	/// Apply action OfferNewer (consuming self — pure transition).
	pub fn offer_newer(self) -> Self {
		let pre = self;
		Self {
			phase: String::from("decided"),
			incoming_attempt: pre.stored_attempt,
			accepted: true,
			stored_attempt: pre.stored_attempt,
		}
	}

	/// Guard for action OfferOlder.
	pub fn can_offer_older(&self) -> bool {
		(self.phase == "stored") && (self.stored_attempt > 1)
	}

	/// Apply action OfferOlder (consuming self — pure transition).
	pub fn offer_older(self) -> Self {
		let pre = self;
		Self {
			phase: String::from("decided"),
			incoming_attempt: (pre.stored_attempt - 1),
			accepted: false,
			stored_attempt: pre.stored_attempt,
		}
	}

	/// Names of actions whose guards hold.
	pub fn enabled_actions(&self) -> Vec<&'static str> {
		let mut out = Vec::new();
		if self.can_store1() {
			out.push("Store1");
		}
		if self.can_store2() {
			out.push("Store2");
		}
		if self.can_store3() {
			out.push("Store3");
		}
		if self.can_offer_newer() {
			out.push("OfferNewer");
		}
		if self.can_offer_older() {
			out.push("OfferOlder");
		}
		out
	}

	/// Apply a named action if its guard holds.
	pub fn apply_action(self, name: &str) -> Option<Self> {
		match name {
			"Store1" => {
				if self.can_store1() {
					Some(self.store1())
				} else {
					None
				}
			}
			"Store2" => {
				if self.can_store2() {
					Some(self.store2())
				} else {
					None
				}
			}
			"Store3" => {
				if self.can_store3() {
					Some(self.store3())
				} else {
					None
				}
			}
			"OfferNewer" => {
				if self.can_offer_newer() {
					Some(self.offer_newer())
				} else {
					None
				}
			}
			"OfferOlder" => {
				if self.can_offer_older() {
					Some(self.offer_older())
				} else {
					None
				}
			}
			_ => None,
		}
	}
}

impl State {
	/// Pure TLA+ operator NoStaleAccepted.
	pub fn no_stale_accepted(&self) -> bool {
		!(self.accepted) || ((self.incoming_attempt >= self.stored_attempt))
	}

	/// Pure TLA+ operator AcceptAllowed.
	pub fn accept_allowed(&self) -> bool {
		(self.incoming_attempt == 0) || (self.incoming_attempt == self.stored_attempt)
	}

}

/// Named pure predicates for dual/CI enumeration.
pub struct PurePredicate {
	pub name: &'static str,
	pub check: fn(&State) -> bool,
}

/// Every pure operator emitted for this module.
pub const PURE_PREDICATES: &[PurePredicate] = &[
	PurePredicate { name: "NoStaleAccepted", check: State::no_stale_accepted },
	PurePredicate { name: "AcceptAllowed", check: State::accept_allowed },
];

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn init_ok() {
		let s = State::init();
		let _ = s.enabled_actions();
	}

	#[test]
	fn pure_predicates_no_panic() {
		let s = State::init();
		assert_eq!(PURE_PREDICATES.len(), 2);
		for p in PURE_PREDICATES {
			let _ = (p.check)(&s);
		}
	}
}
