// Code generated by specgen from specs/timing-clamp/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/timing-clamp/decision/Decision.tla
// Regenerate: bazel run //tools/decision:update
//
// Edit the .tla, not this file. Language: Rust (PATH A decision core).
// Package/module hint: timingclampspec

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct State {
	pub phase: String,
	pub start: i64,
	pub end: i64,
	pub parent_start: i64,
	pub parent_end: i64,
	pub out_start: i64,
	pub out_end: i64,
}

impl State {
	/// Initial state from the TLA+ Init predicate.
	pub fn init() -> Self {
		Self {
			phase: String::from("init"),
			start: 2,
			end: 4,
			parent_start: 1,
			parent_end: 3,
			out_start: 0,
			out_end: 0,
		}
	}

	/// Guard for action SetHostile.
	pub fn can_set_hostile(&self) -> bool {
		self.phase == "init"
	}

	/// Apply action SetHostile (consuming self — pure transition).
	pub fn set_hostile(self) -> Self {
		let pre = self;
		Self {
			start: 0,
			end: 4,
			parent_start: 2,
			parent_end: 3,
			phase: pre.phase,
			out_start: pre.out_start,
			out_end: pre.out_end,
		}
	}

	/// Guard for action DoClamp.
	pub fn can_do_clamp(&self) -> bool {
		(self.phase == "init") && !(false)
	}

	/// Apply action DoClamp (consuming self — pure transition).
	pub fn do_clamp(self) -> Self {
		let pre = self;
		Self {
			phase: String::from("clamped"),
			out_start: (if pre.start < pre.parent_start { pre.parent_start } else { if pre.start > ((if pre.parent_end <= pre.parent_start { pre.parent_start + 1 } else { pre.parent_end }) - 1) { (if pre.parent_end <= pre.parent_start { pre.parent_start + 1 } else { pre.parent_end }) - 1 } else { pre.start } }),
			out_end: (if (if pre.end > (if pre.parent_end <= pre.parent_start { pre.parent_start + 1 } else { pre.parent_end }) { if pre.parent_end <= pre.parent_start { pre.parent_start + 1 } else { pre.parent_end } } else { pre.end }) < ((if pre.start < pre.parent_start { pre.parent_start } else { if pre.start > ((if pre.parent_end <= pre.parent_start { pre.parent_start + 1 } else { pre.parent_end }) - 1) { (if pre.parent_end <= pre.parent_start { pre.parent_start + 1 } else { pre.parent_end }) - 1 } else { pre.start } }) + 1) { (if pre.start < pre.parent_start { pre.parent_start } else { if pre.start > ((if pre.parent_end <= pre.parent_start { pre.parent_start + 1 } else { pre.parent_end }) - 1) { (if pre.parent_end <= pre.parent_start { pre.parent_start + 1 } else { pre.parent_end }) - 1 } else { pre.start } }) + 1 } else { if pre.end > (if pre.parent_end <= pre.parent_start { pre.parent_start + 1 } else { pre.parent_end }) { if pre.parent_end <= pre.parent_start { pre.parent_start + 1 } else { pre.parent_end } } else { pre.end } }),
			start: pre.start,
			end: pre.end,
			parent_start: pre.parent_start,
			parent_end: pre.parent_end,
		}
	}

	/// Guard for action BugPassthrough.
	pub fn can_bug_passthrough(&self) -> bool {
		(self.phase == "init") && false
	}

	/// Apply action BugPassthrough (consuming self — pure transition).
	pub fn bug_passthrough(self) -> Self {
		let pre = self;
		Self {
			phase: String::from("clamped"),
			out_start: pre.start,
			out_end: pre.end,
			start: pre.start,
			end: pre.end,
			parent_start: pre.parent_start,
			parent_end: pre.parent_end,
		}
	}

	/// Guard for action Finish.
	pub fn can_finish(&self) -> bool {
		self.phase == "clamped"
	}

	/// Apply action Finish (consuming self — pure transition).
	pub fn finish(self) -> Self {
		let pre = self;
		Self {
			phase: String::from("done"),
			start: pre.start,
			end: pre.end,
			parent_start: pre.parent_start,
			parent_end: pre.parent_end,
			out_start: pre.out_start,
			out_end: pre.out_end,
		}
	}

	/// Names of actions whose guards hold.
	pub fn enabled_actions(&self) -> Vec<&'static str> {
		let mut out = Vec::new();
		if self.can_set_hostile() {
			out.push("SetHostile");
		}
		if self.can_do_clamp() {
			out.push("DoClamp");
		}
		if self.can_bug_passthrough() {
			out.push("BugPassthrough");
		}
		if self.can_finish() {
			out.push("Finish");
		}
		out
	}

	/// Apply a named action if its guard holds.
	pub fn apply_action(self, name: &str) -> Option<Self> {
		match name {
			"SetHostile" => {
				if self.can_set_hostile() {
					Some(self.set_hostile())
				} else {
					None
				}
			}
			"DoClamp" => {
				if self.can_do_clamp() {
					Some(self.do_clamp())
				} else {
					None
				}
			}
			"BugPassthrough" => {
				if self.can_bug_passthrough() {
					Some(self.bug_passthrough())
				} else {
					None
				}
			}
			"Finish" => {
				if self.can_finish() {
					Some(self.finish())
				} else {
					None
				}
			}
			_ => None,
		}
	}
}

impl State {
	/// Pure TLA+ operator ClampedOrdered.
	pub fn clamped_ordered(&self) -> bool {
		!(((self.phase == "clamped") || (self.phase == "done"))) || ((self.out_start < self.out_end))
	}

	/// Pure TLA+ operator ClampedContained.
	pub fn clamped_contained(&self) -> bool {
		!(((self.phase == "clamped") || (self.phase == "done"))) || (((self.out_start >= self.parent_start) && (!((self.parent_end > self.parent_start)) || (((self.out_start <= (self.parent_end - 1)) && (self.out_end <= self.parent_end))))))
	}

}

/// Named pure predicates for dual/CI enumeration.
pub struct PurePredicate {
	pub name: &'static str,
	pub check: fn(&State) -> bool,
}

/// Every pure operator emitted for this module.
pub const PURE_PREDICATES: &[PurePredicate] = &[
	PurePredicate { name: "ClampedOrdered", check: State::clamped_ordered },
	PurePredicate { name: "ClampedContained", check: State::clamped_contained },
];

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn init_ok() {
		let s = State::init();
		let _ = s.enabled_actions();
	}

	#[test]
	fn pure_predicates_no_panic() {
		let s = State::init();
		assert_eq!(PURE_PREDICATES.len(), 2);
		for p in PURE_PREDICATES {
			let _ = (p.check)(&s);
		}
	}
}
