// Code generated by specgen from specs/tui-reload/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/tui-reload/decision/Decision.tla
// Regenerate: bazel run //tools/decision:update
//
// Edit the .tla, not this file. Language: Rust (PATH A decision core).
// Package/module hint: tuireloadspec

#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
pub struct State {
	pub is_loading: bool,
	pub reload_gen: i64,
	pub fetch_job: i64,
	pub fetch_gen: i64,
	pub stale_accepted: bool,
}

impl State {
	/// Initial state from the TLA+ Init predicate.
	pub fn init() -> Self {
		Self {
			is_loading: false,
			reload_gen: 0,
			fetch_job: 0,
			fetch_gen: 0,
			stale_accepted: false,
		}
	}

	/// Guard for action PressReload.
	pub fn can_press_reload(&self) -> bool {
		(false || !(self.is_loading)) && (self.reload_gen < 2)
	}

	/// Apply action PressReload (consuming self — pure transition).
	pub fn press_reload(self) -> Self {
		let pre = self;
		Self {
			is_loading: true,
			reload_gen: pre.reload_gen,
			fetch_job: pre.fetch_job,
			fetch_gen: pre.fetch_gen,
			stale_accepted: pre.stale_accepted,
		}
	}

	/// Guard for action ReloadDone.
	pub fn can_reload_done(&self) -> bool {
		self.is_loading && (self.reload_gen < 2)
	}

	/// Apply action ReloadDone (consuming self — pure transition).
	pub fn reload_done(self) -> Self {
		let pre = self;
		Self {
			is_loading: false,
			reload_gen: (pre.reload_gen + 1),
			fetch_job: pre.fetch_job,
			fetch_gen: pre.fetch_gen,
			stale_accepted: pre.stale_accepted,
		}
	}

	/// Guard for action PressFetch1.
	pub fn can_press_fetch1(&self) -> bool {
		!(self.is_loading) && (self.fetch_job == 0)
	}

	/// Apply action PressFetch1 (consuming self — pure transition).
	pub fn press_fetch1(self) -> Self {
		let pre = self;
		Self {
			fetch_job: 1,
			fetch_gen: pre.reload_gen,
			is_loading: pre.is_loading,
			reload_gen: pre.reload_gen,
			stale_accepted: pre.stale_accepted,
		}
	}

	/// Guard for action PressFetch2.
	pub fn can_press_fetch2(&self) -> bool {
		!(self.is_loading) && (self.fetch_job == 0)
	}

	/// Apply action PressFetch2 (consuming self — pure transition).
	pub fn press_fetch2(self) -> Self {
		let pre = self;
		Self {
			fetch_job: 2,
			fetch_gen: pre.reload_gen,
			is_loading: pre.is_loading,
			reload_gen: pre.reload_gen,
			stale_accepted: pre.stale_accepted,
		}
	}

	/// Guard for action FetchAccept.
	pub fn can_fetch_accept(&self) -> bool {
		(self.fetch_job != 0) && (self.fetch_gen == self.reload_gen)
	}

	/// Apply action FetchAccept (consuming self — pure transition).
	pub fn fetch_accept(self) -> Self {
		let pre = self;
		Self {
			fetch_job: 0,
			is_loading: pre.is_loading,
			reload_gen: pre.reload_gen,
			fetch_gen: pre.fetch_gen,
			stale_accepted: pre.stale_accepted,
		}
	}

	/// Guard for action FetchDiscard.
	pub fn can_fetch_discard(&self) -> bool {
		(self.fetch_job != 0) && (self.fetch_gen != self.reload_gen)
	}

	/// Apply action FetchDiscard (consuming self — pure transition).
	pub fn fetch_discard(self) -> Self {
		let pre = self;
		Self {
			fetch_job: 0,
			is_loading: pre.is_loading,
			reload_gen: pre.reload_gen,
			fetch_gen: pre.fetch_gen,
			stale_accepted: pre.stale_accepted,
		}
	}

	/// Guard for action FetchStaleBug.
	pub fn can_fetch_stale_bug(&self) -> bool {
		(false && (self.fetch_job != 0)) && (self.fetch_gen != self.reload_gen)
	}

	/// Apply action FetchStaleBug (consuming self — pure transition).
	pub fn fetch_stale_bug(self) -> Self {
		let pre = self;
		Self {
			stale_accepted: true,
			fetch_job: 0,
			is_loading: pre.is_loading,
			reload_gen: pre.reload_gen,
			fetch_gen: pre.fetch_gen,
		}
	}

	/// Names of actions whose guards hold.
	pub fn enabled_actions(&self) -> Vec<&'static str> {
		let mut out = Vec::new();
		if self.can_press_reload() {
			out.push("PressReload");
		}
		if self.can_reload_done() {
			out.push("ReloadDone");
		}
		if self.can_press_fetch1() {
			out.push("PressFetch1");
		}
		if self.can_press_fetch2() {
			out.push("PressFetch2");
		}
		if self.can_fetch_accept() {
			out.push("FetchAccept");
		}
		if self.can_fetch_discard() {
			out.push("FetchDiscard");
		}
		if self.can_fetch_stale_bug() {
			out.push("FetchStaleBug");
		}
		out
	}

	/// Apply a named action if its guard holds.
	pub fn apply_action(self, name: &str) -> Option<Self> {
		match name {
			"PressReload" => {
				if self.can_press_reload() {
					Some(self.press_reload())
				} else {
					None
				}
			}
			"ReloadDone" => {
				if self.can_reload_done() {
					Some(self.reload_done())
				} else {
					None
				}
			}
			"PressFetch1" => {
				if self.can_press_fetch1() {
					Some(self.press_fetch1())
				} else {
					None
				}
			}
			"PressFetch2" => {
				if self.can_press_fetch2() {
					Some(self.press_fetch2())
				} else {
					None
				}
			}
			"FetchAccept" => {
				if self.can_fetch_accept() {
					Some(self.fetch_accept())
				} else {
					None
				}
			}
			"FetchDiscard" => {
				if self.can_fetch_discard() {
					Some(self.fetch_discard())
				} else {
					None
				}
			}
			"FetchStaleBug" => {
				if self.can_fetch_stale_bug() {
					Some(self.fetch_stale_bug())
				} else {
					None
				}
			}
			_ => None,
		}
	}
}

impl State {
	/// Pure TLA+ operator NoStaleAccepted.
	pub fn no_stale_accepted(&self) -> bool {
		!(self.stale_accepted)
	}

}

/// Named pure predicates for dual/CI enumeration.
pub struct PurePredicate {
	pub name: &'static str,
	pub check: fn(&State) -> bool,
}

/// Every pure operator emitted for this module.
pub const PURE_PREDICATES: &[PurePredicate] = &[
	PurePredicate { name: "NoStaleAccepted", check: State::no_stale_accepted },
];

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn init_ok() {
		let s = State::init();
		let _ = s.enabled_actions();
	}

	#[test]
	fn pure_predicates_no_panic() {
		let s = State::init();
		assert_eq!(PURE_PREDICATES.len(), 1);
		for p in PURE_PREDICATES {
			let _ = (p.check)(&s);
		}
	}
}
