load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "analyzer",
    srcs = [
        "analyzer.go",
        "artifacts.go",
        "data_provider.go",
        "facet.go",
        "hourly.go",
        "logspans.go",
        "metrics.go",
        "otel_explorer.go",
        "rundiff.go",
        "spans_summary.go",
        "trace.go",
        "trace_emitter.go",
        "tree.go",
        "trends.go",
        "types.go",
        "typical.go",
    ],
    importpath = "github.com/stefanpenner/otel-explorer/pkg/analyzer",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/enrichment",
        "//pkg/githubapi",
        "//pkg/ingest/otlpfile",
        "//pkg/logparse",
        "//pkg/utils",
        "@com_github_cockroachdb_errors//:errors",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//codes",
        "@io_opentelemetry_go_otel_sdk//trace",
        "@io_opentelemetry_go_otel_sdk//trace/tracetest",
        "@io_opentelemetry_go_otel_trace//:trace",
    ],
)

go_test(
    name = "analyzer_test",
    srcs = [
        "clamp_test.go",
        "data_provider_test.go",
        "facet_test.go",
        "hourly_test.go",
        "mapping_test.go",
        "metrics_test.go",
        "otel_test.go",
        "rundiff_test.go",
        "spans_summary_test.go",
        "trends_test.go",
        "typical_test.go",
    ],
    embed = [":analyzer"],
    deps = [
        "//pkg/enrichment",
        "//pkg/githubapi",
        "//pkg/utils",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
        "@com_github_stretchr_testify//require",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//codes",
        "@io_opentelemetry_go_otel_sdk//trace",
        "@io_opentelemetry_go_otel_sdk//trace/tracetest",
        "@io_opentelemetry_go_otel_trace//:trace",
    ],
)
