// Code generated by specgen from specs/rate-limit/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/rate-limit/decision/Decision.tla
// Regenerate: bazel run //tools/decision:update
//
// Edit the spec, not this file: change the .tla above and re-run the command.

package ratelimitspec

// State mirrors the TLA+ VARIABLES.
type State struct {
	Remaining          int64
	Sleeping           bool
	Clock              int64
	ResetAt            int64
	SentWhileExhausted bool
}

// Init returns the initial state from the TLA+ Init predicate.
func Init() State {
	s := State{
		Remaining:          2,
		Sleeping:           false,
		Clock:              0,
		ResetAt:            0,
		SentWhileExhausted: false,
	}
	return s
}

// CanLearnExhausted is the guard for the LearnExhausted action.
func (s State) CanLearnExhausted() bool {
	return (s.Remaining > 0 && s.Clock < 3)
}

// LearnExhausted applies the LearnExhausted action, returning a new state.
func (s State) LearnExhausted() State {
	pre := s
	s.Remaining = 0
	s.ResetAt = pre.Clock + 1
	return s
}

// CanStartSleep is the guard for the StartSleep action.
func (s State) CanStartSleep() bool {
	return (((s.Remaining == 0 && !(s.Sleeping)) && s.Clock < s.ResetAt) && s.ResetAt > 0)
}

// StartSleep applies the StartSleep action, returning a new state.
func (s State) StartSleep() State {
	s.Sleeping = true
	return s
}

// CanWakeRecheckSend is the guard for the WakeRecheckSend action.
func (s State) CanWakeRecheckSend() bool {
	return (s.Sleeping && !((s.Remaining == 0 && s.ResetAt > 0) && s.Clock < s.ResetAt))
}

// WakeRecheckSend applies the WakeRecheckSend action, returning a new state.
func (s State) WakeRecheckSend() State {
	s.Sleeping = false
	s.Remaining = 2
	return s
}

// CanWakeRecheckResleep is the guard for the WakeRecheckResleep action.
func (s State) CanWakeRecheckResleep() bool {
	return ((((!(false) && s.Sleeping) && s.Remaining == 0) && s.ResetAt > 0) && s.Clock < s.ResetAt)
}

// WakeRecheckResleep applies the WakeRecheckResleep action, returning a new state.
func (s State) WakeRecheckResleep() State {
	return s
}

// CanWakeBugSend is the guard for the WakeBugSend action.
func (s State) CanWakeBugSend() bool {
	return (false && s.Sleeping)
}

// WakeBugSend applies the WakeBugSend action, returning a new state.
func (s State) WakeBugSend() State {
	pre := s
	s.Sleeping = false
	s.SentWhileExhausted = ((pre.Remaining == int64(0) && pre.ResetAt > int64(0)) && pre.Clock < pre.ResetAt)
	s.Remaining = specgenIf(((pre.Remaining == 0 && pre.ResetAt > 0) && pre.Clock < pre.ResetAt), pre.Remaining, 2)
	return s
}

// CanTick is the guard for the Tick action.
func (s State) CanTick() bool {
	return s.Clock < 3
}

// Tick applies the Tick action, returning a new state.
func (s State) Tick() State {
	pre := s
	s.Clock = pre.Clock + 1
	s.Remaining = specgenIf(((pre.Remaining == 0 && pre.ResetAt > 0) && pre.Clock+1 >= pre.ResetAt), 2, pre.Remaining)
	return s
}

// CanSendOk is the guard for the SendOk action.
func (s State) CanSendOk() bool {
	return (s.Remaining > 0 && !(s.Sleeping))
}

// SendOk applies the SendOk action, returning a new state.
func (s State) SendOk() State {
	pre := s
	s.Remaining = pre.Remaining - 1
	return s
}

// EnabledActions returns the names of actions whose guards are satisfied.
func (s State) EnabledActions() []string {
	var out []string
	if s.CanLearnExhausted() {
		out = append(out, "LearnExhausted")
	}
	if s.CanStartSleep() {
		out = append(out, "StartSleep")
	}
	if s.CanWakeRecheckSend() {
		out = append(out, "WakeRecheckSend")
	}
	if s.CanWakeRecheckResleep() {
		out = append(out, "WakeRecheckResleep")
	}
	if s.CanWakeBugSend() {
		out = append(out, "WakeBugSend")
	}
	if s.CanTick() {
		out = append(out, "Tick")
	}
	if s.CanSendOk() {
		out = append(out, "SendOk")
	}
	return out
}

// --- Pure operators (no primed vars; not actions) ---

// WaitNeeded is the pure TLA+ operator WaitNeeded.
func (s State) WaitNeeded() bool {
	return ((s.Remaining == 0 && s.ResetAt > 0) && s.Clock < s.ResetAt)
}

// NoSendWhileExhausted is the pure TLA+ operator NoSendWhileExhausted.
func (s State) NoSendWhileExhausted() bool {
	return !(s.SentWhileExhausted)
}

// PurePredicate is a named pure decision gate (no state change).
type PurePredicate struct {
	Name  string
	Check func(State) bool
}

// PurePredicates returns every pure operator emitted for this module.
func PurePredicates() []PurePredicate {
	return []PurePredicate{
		{Name: "WaitNeeded", Check: State.WaitNeeded},
		{Name: "NoSendWhileExhausted", Check: State.NoSendWhileExhausted},
	}
}

// --- Trace emission for conformance checking ---

// TraceEntry is a single recorded transition for conformance validation.
// Arg and Consts are empty/nil for a named action (PATH A); for a
// Step-dispatch spec (PATH B), Arg carries the input value Step was called
// with, and Consts carries the value of every free CONSTANT parameter (e.g.
// HasSel) — without it, a replayed trace couldn't reconstruct what Step
// actually saw whenever a free var varies between calls.
type TraceEntry struct {
	Action string          `json:"action"`
	Arg    string          `json:"arg,omitempty"`
	Args   []string        `json:"args,omitempty"`
	Consts map[string]bool `json:"consts,omitempty"`
	Pre    State           `json:"pre"`
	Post   State           `json:"post"`
}

// ApplyAction dispatches a named action, returning the new state.
// Panics on unknown action names.
func (s State) ApplyAction(name string) State {
	switch name {
	case "LearnExhausted":
		return s.LearnExhausted()
	case "StartSleep":
		return s.StartSleep()
	case "WakeRecheckSend":
		return s.WakeRecheckSend()
	case "WakeRecheckResleep":
		return s.WakeRecheckResleep()
	case "WakeBugSend":
		return s.WakeBugSend()
	case "Tick":
		return s.Tick()
	case "SendOk":
		return s.SendOk()
	default:
		panic("unknown action: " + name)
	}
}

// Trace records a transition: applies the action and returns
// both the trace entry and the new state.
func (s State) Trace(action string) (TraceEntry, State) {
	pre := s
	post := s.ApplyAction(action)
	return TraceEntry{
		Action: action,
		Pre:    pre,
		Post:   post,
	}, post
}

// specgenIf evaluates a TLA+ IF/THEN/ELSE used as a value.
func specgenIf[T any](cond bool, then, els T) T {
	if cond {
		return then
	}
	return els
}
