// Code generated by specgen — DO NOT EDIT.

package ratelimitspec

import (
	"fmt"
	"testing"
)

func TestInit(t *testing.T) {
	s := Init()
	if s.Remaining != int64(2) {
		t.Errorf("Remaining = %v, want %v", s.Remaining, int64(2))
	}
	if s.Sleeping != bool(false) {
		t.Errorf("Sleeping = %v, want %v", s.Sleeping, bool(false))
	}
	if s.Clock != int64(0) {
		t.Errorf("Clock = %v, want %v", s.Clock, int64(0))
	}
	if s.ResetAt != int64(0) {
		t.Errorf("ResetAt = %v, want %v", s.ResetAt, int64(0))
	}
	if s.SentWhileExhausted != bool(false) {
		t.Errorf("SentWhileExhausted = %v, want %v", s.SentWhileExhausted, bool(false))
	}
}

// TestBFSReachability walks the state space from Init, applying every
// enabled action. Verifies no transition panics and all states are reachable.
func TestBFSReachability(t *testing.T) {
	seen := map[string]bool{}
	queue := []State{Init()}
	maxStates := 10000

	for len(queue) > 0 && len(seen) < maxStates {
		s := queue[0]
		queue = queue[1:]
		key := fmt.Sprintf("%+v", s)
		if seen[key] {
			continue
		}
		seen[key] = true

		for _, action := range s.EnabledActions() {
			next := s.ApplyAction(action)
			queue = append(queue, next)
		}
	}

	if len(seen) == 0 {
		t.Fatal("no reachable states")
	}
	t.Logf("explored %d reachable states", len(seen))
}
