// Code generated by specgen from specs/log-groups/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/log-groups/decision/Decision.tla
// Regenerate: bazel run //tools/decision:update
//
// Edit the spec, not this file: change the .tla above and re-run the command.

package loggroupsspec

// State mirrors the TLA+ VARIABLES.
type State struct {
	Depth int64
}

// Init returns the initial state from the TLA+ Init predicate.
func Init() State {
	s := State{
		Depth: 0,
	}
	return s
}

// CanOpen is the guard for the Open action.
func (s State) CanOpen() bool {
	return (s.Depth >= 0 && s.Depth < 3)
}

// Open applies the Open action, returning a new state.
func (s State) Open() State {
	pre := s
	s.Depth = pre.Depth + 1
	return s
}

// CanClose is the guard for the Close action.
func (s State) CanClose() bool {
	return s.Depth > 0
}

// Close applies the Close action, returning a new state.
func (s State) Close() State {
	pre := s
	s.Depth = pre.Depth - 1
	return s
}

// CanCloseBug is the guard for the CloseBug action.
func (s State) CanCloseBug() bool {
	return (false && s.Depth == 0)
}

// CloseBug applies the CloseBug action, returning a new state.
func (s State) CloseBug() State {
	pre := s
	s.Depth = pre.Depth - 1
	return s
}

// CanTerminating is the guard for the Terminating action.
func (s State) CanTerminating() bool {
	return true
}

// Terminating applies the Terminating action, returning a new state.
func (s State) Terminating() State {
	return s
}

// EnabledActions returns the names of actions whose guards are satisfied.
func (s State) EnabledActions() []string {
	var out []string
	if s.CanOpen() {
		out = append(out, "Open")
	}
	if s.CanClose() {
		out = append(out, "Close")
	}
	if s.CanCloseBug() {
		out = append(out, "CloseBug")
	}
	if s.CanTerminating() {
		out = append(out, "Terminating")
	}
	return out
}

// --- Pure operators (no primed vars; not actions) ---

// Inv_DepthNonNeg is the pure TLA+ operator Inv_DepthNonNeg.
func (s State) Inv_DepthNonNeg() bool {
	return s.Depth >= 0
}

// PurePredicate is a named pure decision gate (no state change).
type PurePredicate struct {
	Name  string
	Check func(State) bool
}

// PurePredicates returns every pure operator emitted for this module.
func PurePredicates() []PurePredicate {
	return []PurePredicate{
		{Name: "Inv_DepthNonNeg", Check: State.Inv_DepthNonNeg},
	}
}

// --- Trace emission for conformance checking ---

// TraceEntry is a single recorded transition for conformance validation.
// Arg and Consts are empty/nil for a named action (PATH A); for a
// Step-dispatch spec (PATH B), Arg carries the input value Step was called
// with, and Consts carries the value of every free CONSTANT parameter (e.g.
// HasSel) — without it, a replayed trace couldn't reconstruct what Step
// actually saw whenever a free var varies between calls.
type TraceEntry struct {
	Action string          `json:"action"`
	Arg    string          `json:"arg,omitempty"`
	Args   []string        `json:"args,omitempty"`
	Consts map[string]bool `json:"consts,omitempty"`
	Pre    State           `json:"pre"`
	Post   State           `json:"post"`
}

// ApplyAction dispatches a named action, returning the new state.
// Panics on unknown action names.
func (s State) ApplyAction(name string) State {
	switch name {
	case "Open":
		return s.Open()
	case "Close":
		return s.Close()
	case "CloseBug":
		return s.CloseBug()
	case "Terminating":
		return s.Terminating()
	default:
		panic("unknown action: " + name)
	}
}

// Trace records a transition: applies the action and returns
// both the trace entry and the new state.
func (s State) Trace(action string) (TraceEntry, State) {
	pre := s
	post := s.ApplyAction(action)
	return TraceEntry{
		Action: action,
		Pre:    pre,
		Post:   post,
	}, post
}
