load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tui",
    srcs = ["progress.go"],
    importpath = "github.com/stefanpenner/otel-explorer/pkg/tui",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_charmbracelet_bubbles//spinner",
        "@com_github_charmbracelet_bubbletea//:bubbletea",
        "@com_github_charmbracelet_lipgloss//:lipgloss",
    ],
)

go_test(
    name = "tui_test",
    srcs = ["progress_test.go"],
    embed = [":tui"],
    deps = ["@com_github_charmbracelet_bubbles//spinner"],
)
