package export

import (
	"encoding/json"
	"io"
	"strings"
)

// RenderSlack writes a Slack Block Kit message (JSON) for the report: a header,
// KPI fields, and the key findings as mrkdwn sections with severity emoji. The
// payload is ready to POST to an incoming webhook or the chat.postMessage API,
// or to paste into Slack's Block Kit Builder. A plain-text `text` fallback is
// included for notifications and accessibility.
func RenderSlack(w io.Writer, rep *Report) error {
	msg := slackMessage{Text: slackFallback(rep), Blocks: slackBlocks(rep)}
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	return enc.Encode(msg)
}

type slackMessage struct {
	Text   string       `json:"text"`
	Blocks []slackBlock `json:"blocks"`
}

type slackBlock struct {
	Type     string      `json:"type"`
	Text     *slackText  `json:"text,omitempty"`
	Fields   []slackText `json:"fields,omitempty"`
	Elements []slackText `json:"elements,omitempty"`
}

type slackText struct {
	Type  string `json:"type"`
	Text  string `json:"text"`
	Emoji *bool  `json:"emoji,omitempty"`
}

func mrkdwn(s string) *slackText { return &slackText{Type: "mrkdwn", Text: s} }

func slackBlocks(rep *Report) []slackBlock {
	var blocks []slackBlock

	title := "CI Run Analysis"
	if rep.Kind == KindTrends {
		title = sprintf("CI Trends · last %d days", rep.Trends.Days)
	}
	if rep.Meta.Repo != "" {
		title += " · " + rep.Meta.Repo
	}
	t := true
	blocks = append(blocks, slackBlock{Type: "header", Text: &slackText{Type: "plain_text", Text: truncate(title, 150), Emoji: &t}})
	blocks = append(blocks, slackBlock{Type: "context", Elements: []slackText{*mrkdwn(sprintf("%s · generated %s", slackEscape(leadSentence(rep)), rep.Meta.GeneratedAt))}})

	// KPI fields (Slack allows up to 10 per section).
	var kpis []kpi
	if rep.Kind == KindTrends {
		kpis = trendKPIs(rep.Trends)
	} else {
		kpis = runKPIs(rep.Run)
	}
	var fields []slackText
	for i, k := range kpis {
		if i >= 10 {
			break
		}
		val := k.Value
		if k.Sub != "" {
			val += "  _" + slackEscape(k.Sub) + "_"
		}
		fields = append(fields, *mrkdwn(sprintf("*%s*\n%s", slackEscape(k.Label), val)))
	}
	if len(fields) > 0 {
		blocks = append(blocks, slackBlock{Type: "section", Fields: fields})
	}

	// Key findings.
	hl := reportHighlights(rep)
	if len(hl) > 0 {
		blocks = append(blocks, slackBlock{Type: "divider"})
		blocks = append(blocks, slackBlock{Type: "section", Text: mrkdwn("*Key findings*")})
		for _, in := range hl {
			text := sprintf("%s *%s*", slackEmoji(in.Severity), slackEscape(in.Title))
			if in.Detail != "" {
				text += "\n" + slackEscape(in.Detail)
			}
			if in.Recommendation != "" {
				rec := slackEscape(in.Recommendation)
				if in.URL != "" {
					rec = sprintf("<%s|%s>", in.URL, rec)
				}
				text += "\n→ " + rec
			}
			blocks = append(blocks, slackBlock{Type: "section", Text: mrkdwn(text)})
		}
	}

	blocks = append(blocks, slackBlock{Type: "context", Elements: []slackText{*mrkdwn("Generated by ote")}})
	return blocks
}

func slackFallback(rep *Report) string {
	repo := ""
	if rep.Meta.Repo != "" {
		repo = " " + rep.Meta.Repo
	}
	if rep.Kind == KindTrends {
		t := rep.Trends
		return sprintf("CI Trends%s: %.0f%% success over %d runs, trend %s", repo, t.Summary.AvgSuccessRatePct, t.Summary.TotalRuns, t.Summary.TrendDirection)
	}
	r := rep.Run
	return sprintf("CI Run Analysis%s: %s job success, %d/%d jobs failed", repo, pctText(r.Summary.JobSuccessRatePct), r.Summary.FailedJobs, r.Summary.TotalJobs)
}

func slackEmoji(s Severity) string {
	switch s {
	case SeverityBad:
		return ":red_circle:"
	case SeverityWarn:
		return ":large_yellow_circle:"
	case SeverityGood:
		return ":large_green_circle:"
	default:
		return ":large_blue_circle:"
	}
}

// slackEscape escapes the three characters Slack treats specially in mrkdwn.
func slackEscape(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	return s
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	if n <= 1 {
		return s[:n]
	}
	return s[:n-1] + "…"
}
