// Code generated by specgen — DO NOT EDIT.

package syncboundsspec

import (
	"fmt"
	"testing"
)

func TestInit(t *testing.T) {
	s := Init()
	if s.Phase != string("empty") {
		t.Errorf("Phase = %v, want %v", s.Phase, string("empty"))
	}
	if s.StoredAttempt != int64(0) {
		t.Errorf("StoredAttempt = %v, want %v", s.StoredAttempt, int64(0))
	}
	if s.IncomingAttempt != int64(0) {
		t.Errorf("IncomingAttempt = %v, want %v", s.IncomingAttempt, int64(0))
	}
	if s.Accepted != bool(false) {
		t.Errorf("Accepted = %v, want %v", s.Accepted, bool(false))
	}
}

// TestBFSReachability walks the state space from Init, applying every
// enabled action. Verifies no transition panics and all states are reachable.
func TestBFSReachability(t *testing.T) {
	seen := map[string]bool{}
	queue := []State{Init()}
	maxStates := 10000

	for len(queue) > 0 && len(seen) < maxStates {
		s := queue[0]
		queue = queue[1:]
		key := fmt.Sprintf("%+v", s)
		if seen[key] {
			continue
		}
		seen[key] = true

		for _, action := range s.EnabledActions() {
			next := s.ApplyAction(action)
			queue = append(queue, next)
		}
	}

	if len(seen) == 0 {
		t.Fatal("no reachable states")
	}
	t.Logf("explored %d reachable states", len(seen))
}

// TestPurePredicates is the generated pure-gate dual stub.
// Names come from Decision.tla (SSOT); dual package tests cover production wiring.
func TestPurePredicates(t *testing.T) {
	want := []string{
		"NoStaleAccepted",
	}
	s := Init()
	preds := PurePredicates()
	if len(preds) != len(want) {
		t.Fatalf("PurePredicates len=%d want %d", len(preds), len(want))
	}
	got := make(map[string]bool, len(preds))
	for _, p := range preds {
		if p.Name == "" {
			t.Fatal("empty PurePredicate.Name")
		}
		if got[p.Name] {
			t.Fatalf("duplicate pure name %q", p.Name)
		}
		got[p.Name] = true
		t.Run(p.Name, func(t *testing.T) {
			_ = p.Check(s) // must not panic
		})
	}
	for _, name := range want {
		if !got[name] {
			t.Fatalf("missing pure %q in PurePredicates()", name)
		}
	}
}
