// Code generated by specgen — DO NOT EDIT.

package syncboundsspec

import (
	"fmt"
	"testing"
)

func TestInit(t *testing.T) {
	s := Init()
	if s.Phase != string("empty") {
		t.Errorf("Phase = %v, want %v", s.Phase, string("empty"))
	}
	if s.StoredAttempt != int64(0) {
		t.Errorf("StoredAttempt = %v, want %v", s.StoredAttempt, int64(0))
	}
	if s.IncomingAttempt != int64(0) {
		t.Errorf("IncomingAttempt = %v, want %v", s.IncomingAttempt, int64(0))
	}
	if s.Accepted != bool(false) {
		t.Errorf("Accepted = %v, want %v", s.Accepted, bool(false))
	}
}

// TestBFSReachability walks the state space from Init, applying every
// enabled action. Verifies no transition panics and all states are reachable.
func TestBFSReachability(t *testing.T) {
	seen := map[string]bool{}
	queue := []State{Init()}
	maxStates := 10000

	for len(queue) > 0 && len(seen) < maxStates {
		s := queue[0]
		queue = queue[1:]
		key := fmt.Sprintf("%+v", s)
		if seen[key] {
			continue
		}
		seen[key] = true

		for _, action := range s.EnabledActions() {
			next := s.ApplyAction(action)
			queue = append(queue, next)
		}
	}

	if len(seen) == 0 {
		t.Fatal("no reachable states")
	}
	t.Logf("explored %d reachable states", len(seen))
}
