// Code generated by specgen from specs/sync-bounds/decision/Decision.tla — DO NOT EDIT.
//
// Source:     specs/sync-bounds/decision/Decision.tla
// Regenerate: specgen -const Bug=FALSE -o pkg/store/syncboundsspec -p syncboundsspec specs/sync-bounds/decision/Decision.tla
//
// Edit the spec, not this file: change the .tla above and re-run the command.

package syncboundsspec

// State mirrors the TLA+ VARIABLES.
type State struct {
	Phase           string
	StoredAttempt   int64
	IncomingAttempt int64
	Accepted        bool
}

// Init returns the initial state from the TLA+ Init predicate.
func Init() State {
	s := State{
		Phase:           "empty",
		StoredAttempt:   0,
		IncomingAttempt: 0,
		Accepted:        false,
	}
	return s
}

// CanStore1 is the guard for the Store1 action.
func (s State) CanStore1() bool {
	return s.Phase == "empty" || s.Phase == "stored"
}

// Store1 applies the Store1 action, returning a new state.
func (s State) Store1() State {
	s.Phase = "stored"
	s.StoredAttempt = 1
	return s
}

// CanStore2 is the guard for the Store2 action.
func (s State) CanStore2() bool {
	return s.Phase == "empty" || s.Phase == "stored"
}

// Store2 applies the Store2 action, returning a new state.
func (s State) Store2() State {
	s.Phase = "stored"
	s.StoredAttempt = 2
	return s
}

// CanStore3 is the guard for the Store3 action.
func (s State) CanStore3() bool {
	return s.Phase == "empty" || s.Phase == "stored"
}

// Store3 applies the Store3 action, returning a new state.
func (s State) Store3() State {
	s.Phase = "stored"
	s.StoredAttempt = 3
	return s
}

// CanOfferNewer is the guard for the OfferNewer action.
func (s State) CanOfferNewer() bool {
	return s.Phase == "stored" && s.StoredAttempt > 0
}

// OfferNewer applies the OfferNewer action, returning a new state.
func (s State) OfferNewer() State {
	pre := s
	s.Phase = "decided"
	s.IncomingAttempt = pre.StoredAttempt
	s.Accepted = true
	return s
}

// CanOfferOlder is the guard for the OfferOlder action.
func (s State) CanOfferOlder() bool {
	return s.Phase == "stored" && s.StoredAttempt > 1
}

// OfferOlder applies the OfferOlder action, returning a new state.
func (s State) OfferOlder() State {
	pre := s
	s.Phase = "decided"
	s.IncomingAttempt = pre.StoredAttempt - 1
	s.Accepted = false
	return s
}

// EnabledActions returns the names of actions whose guards are satisfied.
func (s State) EnabledActions() []string {
	var out []string
	if s.CanStore1() {
		out = append(out, "Store1")
	}
	if s.CanStore2() {
		out = append(out, "Store2")
	}
	if s.CanStore3() {
		out = append(out, "Store3")
	}
	if s.CanOfferNewer() {
		out = append(out, "OfferNewer")
	}
	if s.CanOfferOlder() {
		out = append(out, "OfferOlder")
	}
	return out
}

// --- Pure operators (no primed vars; not actions) ---

// NoStaleAccepted is the pure TLA+ operator NoStaleAccepted.
func (s State) NoStaleAccepted() bool {
	return (!(s.Accepted) || (s.IncomingAttempt >= s.StoredAttempt))
}

// BaitNeverAccepted is the pure TLA+ operator BaitNeverAccepted.
func (s State) BaitNeverAccepted() bool {
	return !(s.Accepted)
}

// --- Trace emission for conformance checking ---

// TraceEntry is a single recorded transition for conformance validation.
// Arg and Consts are empty/nil for a named action (PATH A); for a
// Step-dispatch spec (PATH B), Arg carries the input value Step was called
// with, and Consts carries the value of every free CONSTANT parameter (e.g.
// HasSel) — without it, a replayed trace couldn't reconstruct what Step
// actually saw whenever a free var varies between calls.
type TraceEntry struct {
	Action string          `json:"action"`
	Arg    string          `json:"arg,omitempty"`
	Args   []string        `json:"args,omitempty"`
	Consts map[string]bool `json:"consts,omitempty"`
	Pre    State           `json:"pre"`
	Post   State           `json:"post"`
}

// ApplyAction dispatches a named action, returning the new state.
// Panics on unknown action names.
func (s State) ApplyAction(name string) State {
	switch name {
	case "Store1":
		return s.Store1()
	case "Store2":
		return s.Store2()
	case "Store3":
		return s.Store3()
	case "OfferNewer":
		return s.OfferNewer()
	case "OfferOlder":
		return s.OfferOlder()
	default:
		panic("unknown action: " + name)
	}
}

// Trace records a transition: applies the action and returns
// both the trace entry and the new state.
func (s State) Trace(action string) (TraceEntry, State) {
	pre := s
	post := s.ApplyAction(action)
	return TraceEntry{
		Action: action,
		Pre:    pre,
		Post:   post,
	}, post
}
